/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.FilterRuleUpdate

class FilterRuleUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FilterRuleUpdate
        //val modelInstance = FilterRuleUpdate()

        // to test the property `tag`
        should("test tag") {
            // uncomment below to test the property
            //modelInstance.tag shouldBe ("TODO")
        }

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `intervalSeconds`
        should("test intervalSeconds") {
            // uncomment below to test the property
            //modelInstance.intervalSeconds shouldBe ("TODO")
        }

        // to test the property `maxResultsPerPoll`
        should("test maxResultsPerPoll") {
            // uncomment below to test the property
            //modelInstance.maxResultsPerPoll shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `webhookUrl`
        should("test webhookUrl") {
            // uncomment below to test the property
            //modelInstance.webhookUrl shouldBe ("TODO")
        }

        // to test the property `webhookSecret`
        should("test webhookSecret") {
            // uncomment below to test the property
            //modelInstance.webhookSecret shouldBe ("TODO")
        }

    }
}
