/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.FilterRuleDeliveryLogResponse

class FilterRuleDeliveryLogResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FilterRuleDeliveryLogResponse
        //val modelInstance = FilterRuleDeliveryLogResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `ruleId`
        should("test ruleId") {
            // uncomment below to test the property
            //modelInstance.ruleId shouldBe ("TODO")
        }

        // to test the property `ruleTag`
        should("test ruleTag") {
            // uncomment below to test the property
            //modelInstance.ruleTag shouldBe ("TODO")
        }

        // to test the property `tweetId`
        should("test tweetId") {
            // uncomment below to test the property
            //modelInstance.tweetId shouldBe ("TODO")
        }

        // to test the property `authorUsername`
        should("test authorUsername") {
            // uncomment below to test the property
            //modelInstance.authorUsername shouldBe ("TODO")
        }

        // to test the property `tweetTextPreview`
        should("test tweetTextPreview") {
            // uncomment below to test the property
            //modelInstance.tweetTextPreview shouldBe ("TODO")
        }

        // to test the property `tweetUrl`
        should("test tweetUrl") {
            // uncomment below to test the property
            //modelInstance.tweetUrl shouldBe ("TODO")
        }

        // to test the property `tweetPublishedAt`
        should("test tweetPublishedAt") {
            // uncomment below to test the property
            //modelInstance.tweetPublishedAt shouldBe ("TODO")
        }

        // to test the property `detectedAt`
        should("test detectedAt") {
            // uncomment below to test the property
            //modelInstance.detectedAt shouldBe ("TODO")
        }

        // to test the property `latencyMs`
        should("test latencyMs") {
            // uncomment below to test the property
            //modelInstance.latencyMs shouldBe ("TODO")
        }

        // to test the property `latencyBadge`
        should("test latencyBadge") {
            // uncomment below to test the property
            //modelInstance.latencyBadge shouldBe ("TODO")
        }

        // to test the property `deliveryStatus`
        should("test deliveryStatus") {
            // uncomment below to test the property
            //modelInstance.deliveryStatus shouldBe ("TODO")
        }

        // to test the property `webhookStatusCode`
        should("test webhookStatusCode") {
            // uncomment below to test the property
            //modelInstance.webhookStatusCode shouldBe ("TODO")
        }

        // to test the property `webhookAttempts`
        should("test webhookAttempts") {
            // uncomment below to test the property
            //modelInstance.webhookAttempts shouldBe ("TODO")
        }

    }
}
