/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.FilterRuleResponse

class FilterRuleResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FilterRuleResponse
        //val modelInstance = FilterRuleResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `tag`
        should("test tag") {
            // uncomment below to test the property
            //modelInstance.tag shouldBe ("TODO")
        }

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `intervalSeconds`
        should("test intervalSeconds") {
            // uncomment below to test the property
            //modelInstance.intervalSeconds shouldBe ("TODO")
        }

        // to test the property `maxResultsPerPoll`
        should("test maxResultsPerPoll") {
            // uncomment below to test the property
            //modelInstance.maxResultsPerPoll shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusReason`
        should("test statusReason") {
            // uncomment below to test the property
            //modelInstance.statusReason shouldBe ("TODO")
        }

        // to test the property `webhookUrl`
        should("test webhookUrl") {
            // uncomment below to test the property
            //modelInstance.webhookUrl shouldBe ("TODO")
        }

        // to test the property `webhookSecretSet`
        should("test webhookSecretSet") {
            // uncomment below to test the property
            //modelInstance.webhookSecretSet shouldBe ("TODO")
        }

        // to test the property `totalCreditsBurned`
        should("test totalCreditsBurned") {
            // uncomment below to test the property
            //modelInstance.totalCreditsBurned shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
