/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.MarketsResponse

class MarketsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MarketsResponse
        //val modelInstance = MarketsResponse()

        // to test the property `markets`
        should("test markets") {
            // uncomment below to test the property
            //modelInstance.markets shouldBe ("TODO")
        }

    }
}
