/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse

class PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
        //val modelInstance = PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse()

        // to test the property `creditsPerEmptyCall`
        should("test creditsPerEmptyCall") {
            // uncomment below to test the property
            //modelInstance.creditsPerEmptyCall shouldBe ("TODO")
        }

        // to test the property `creditsPerTweetReturned`
        should("test creditsPerTweetReturned") {
            // uncomment below to test the property
            //modelInstance.creditsPerTweetReturned shouldBe ("TODO")
        }

    }
}
