/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.ScreenshotRequest

class ScreenshotRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScreenshotRequest
        //val modelInstance = ScreenshotRequest()

        // to test the property `url` - The page to fetch.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `waitFor`
        should("test waitFor") {
            // uncomment below to test the property
            //modelInstance.waitFor shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `proxyTier` - Proxy pool: simple, premium or ultra.
        should("test proxyTier") {
            // uncomment below to test the property
            //modelInstance.proxyTier shouldBe ("TODO")
        }

        // to test the property `fullPage` - Capture the whole scrollable page instead of the viewport.
        should("test fullPage") {
            // uncomment below to test the property
            //modelInstance.fullPage shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

    }
}
