/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.StreamMonitorResponse

class StreamMonitorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StreamMonitorResponse
        //val modelInstance = StreamMonitorResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `usernames`
        should("test usernames") {
            // uncomment below to test the property
            //modelInstance.usernames shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusReason`
        should("test statusReason") {
            // uncomment below to test the property
            //modelInstance.statusReason shouldBe ("TODO")
        }

        // to test the property `webhookUrl`
        should("test webhookUrl") {
            // uncomment below to test the property
            //modelInstance.webhookUrl shouldBe ("TODO")
        }

        // to test the property `webhookSecretSet`
        should("test webhookSecretSet") {
            // uncomment below to test the property
            //modelInstance.webhookSecretSet shouldBe ("TODO")
        }

        // to test the property `filterTypes`
        should("test filterTypes") {
            // uncomment below to test the property
            //modelInstance.filterTypes shouldBe ("TODO")
        }

        // to test the property `creditsPerAccountPerDay`
        should("test creditsPerAccountPerDay") {
            // uncomment below to test the property
            //modelInstance.creditsPerAccountPerDay shouldBe ("TODO")
        }

        // to test the property `estimatedCreditsPerDay`
        should("test estimatedCreditsPerDay") {
            // uncomment below to test the property
            //modelInstance.estimatedCreditsPerDay shouldBe ("TODO")
        }

        // to test the property `pricingTier`
        should("test pricingTier") {
            // uncomment below to test the property
            //modelInstance.pricingTier shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
