/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.VintedPhoto

class VintedPhotoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VintedPhoto
        //val modelInstance = VintedPhoto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `dominantColor`
        should("test dominantColor") {
            // uncomment below to test the property
            //modelInstance.dominantColor shouldBe ("TODO")
        }

        // to test the property `isMain`
        should("test isMain") {
            // uncomment below to test the property
            //modelInstance.isMain shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `fullSizeUrl`
        should("test fullSizeUrl") {
            // uncomment below to test the property
            //modelInstance.fullSizeUrl shouldBe ("TODO")
        }

    }
}
