/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.models.VintedImageSearchRequest

class VintedImageSearchRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VintedImageSearchRequest
        //val modelInstance = VintedImageSearchRequest()

        // to test the property `imageUrl`
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `imageBase64`
        should("test imageBase64") {
            // uncomment below to test the property
            //modelInstance.imageBase64 shouldBe ("TODO")
        }

        // to test the property `market` - Vinted market code; uk aliases gb
        should("test market") {
            // uncomment below to test the property
            //modelInstance.market shouldBe ("TODO")
        }

        // to test the property `page`
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `perPage`
        should("test perPage") {
            // uncomment below to test the property
            //modelInstance.perPage shouldBe ("TODO")
        }

        // to test the property `priceFrom`
        should("test priceFrom") {
            // uncomment below to test the property
            //modelInstance.priceFrom shouldBe ("TODO")
        }

        // to test the property `priceTo`
        should("test priceTo") {
            // uncomment below to test the property
            //modelInstance.priceTo shouldBe ("TODO")
        }

        // to test the property `brandIds`
        should("test brandIds") {
            // uncomment below to test the property
            //modelInstance.brandIds shouldBe ("TODO")
        }

        // to test the property `catalogIds`
        should("test catalogIds") {
            // uncomment below to test the property
            //modelInstance.catalogIds shouldBe ("TODO")
        }

        // to test the property `colorIds`
        should("test colorIds") {
            // uncomment below to test the property
            //modelInstance.colorIds shouldBe ("TODO")
        }

        // to test the property `sizeIds`
        should("test sizeIds") {
            // uncomment below to test the property
            //modelInstance.sizeIds shouldBe ("TODO")
        }

        // to test the property `materialIds`
        should("test materialIds") {
            // uncomment below to test the property
            //modelInstance.materialIds shouldBe ("TODO")
        }

        // to test the property `statusIds`
        should("test statusIds") {
            // uncomment below to test the property
            //modelInstance.statusIds shouldBe ("TODO")
        }

        // to test the property `time`
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

        // to test the property `searchSessionId`
        should("test searchSessionId") {
            // uncomment below to test the property
            //modelInstance.searchSessionId shouldBe ("TODO")
        }

    }
}
