/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.scrapebadger.client.models.HTTPValidationError

import com.squareup.moshi.Json

import com.scrapebadger.client.infrastructure.ApiClient
import com.scrapebadger.client.infrastructure.ApiResponse
import com.scrapebadger.client.infrastructure.ClientException
import com.scrapebadger.client.infrastructure.ClientError
import com.scrapebadger.client.infrastructure.ServerException
import com.scrapebadger.client.infrastructure.ServerError
import com.scrapebadger.client.infrastructure.MultiValueMap
import com.scrapebadger.client.infrastructure.PartConfig
import com.scrapebadger.client.infrastructure.RequestConfig
import com.scrapebadger.client.infrastructure.RequestMethod
import com.scrapebadger.client.infrastructure.ResponseType
import com.scrapebadger.client.infrastructure.Success
import com.scrapebadger.client.infrastructure.toMultiValue

class DuckDuckGoApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://scrapebadger.com")
        }
    }

    /**
     * DuckDuckGo scraper health check
     * Check health of the DuckDuckGo scraper service (accepts HEAD for UptimeRobot).
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoDuckduckgoScraperHealthCheck() : kotlin.Any {
        val localVarResponse = duckduckgoDuckduckgoScraperHealthCheckWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DuckDuckGo scraper health check
     * Check health of the DuckDuckGo scraper service (accepts HEAD for UptimeRobot).
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoDuckduckgoScraperHealthCheckWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoDuckduckgoScraperHealthCheckRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoDuckduckgoScraperHealthCheck
     *
     * @return RequestConfig
     */
    fun duckduckgoDuckduckgoScraperHealthCheckRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DuckDuckGo scraper health check
     * Check health of the DuckDuckGo scraper service (accepts HEAD for UptimeRobot).
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoDuckduckgoScraperHealthCheckHead() : kotlin.Any {
        val localVarResponse = duckduckgoDuckduckgoScraperHealthCheckHeadWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DuckDuckGo scraper health check
     * Check health of the DuckDuckGo scraper service (accepts HEAD for UptimeRobot).
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoDuckduckgoScraperHealthCheckHeadWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoDuckduckgoScraperHealthCheckHeadRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoDuckduckgoScraperHealthCheckHead
     *
     * @return RequestConfig
     */
    fun duckduckgoDuckduckgoScraperHealthCheckHeadRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.HEAD,
            path = "/v1/duckduckgo/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Image search
     * DuckDuckGo image search with size/color/type/layout/license filters.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param page 100 results per page (optional, default to 1)
     * @param size Small | Medium | Large | Wallpaper (optional, default to "")
     * @param color color | Monochrome | Red | Blue | … (optional, default to "")
     * @param imageType photo | clipart | gif | transparent | line (optional, default to "")
     * @param layout Square | Tall | Wide (optional, default to "")
     * @param license Any | Public | Share | ShareCommercially | Modify (optional, default to "")
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoImageSearch(query: kotlin.String, region: kotlin.String? = "wt-wt", safesearch: kotlin.String? = "moderate", page: kotlin.Int? = 1, size: kotlin.String? = "", color: kotlin.String? = "", imageType: kotlin.String? = "", layout: kotlin.String? = "", license: kotlin.String? = "") : kotlin.Any {
        val localVarResponse = duckduckgoImageSearchWithHttpInfo(query = query, region = region, safesearch = safesearch, page = page, size = size, color = color, imageType = imageType, layout = layout, license = license)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Image search
     * DuckDuckGo image search with size/color/type/layout/license filters.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param page 100 results per page (optional, default to 1)
     * @param size Small | Medium | Large | Wallpaper (optional, default to "")
     * @param color color | Monochrome | Red | Blue | … (optional, default to "")
     * @param imageType photo | clipart | gif | transparent | line (optional, default to "")
     * @param layout Square | Tall | Wide (optional, default to "")
     * @param license Any | Public | Share | ShareCommercially | Modify (optional, default to "")
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoImageSearchWithHttpInfo(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, page: kotlin.Int?, size: kotlin.String?, color: kotlin.String?, imageType: kotlin.String?, layout: kotlin.String?, license: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoImageSearchRequestConfig(query = query, region = region, safesearch = safesearch, page = page, size = size, color = color, imageType = imageType, layout = layout, license = license)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoImageSearch
     *
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param page 100 results per page (optional, default to 1)
     * @param size Small | Medium | Large | Wallpaper (optional, default to "")
     * @param color color | Monochrome | Red | Blue | … (optional, default to "")
     * @param imageType photo | clipart | gif | transparent | line (optional, default to "")
     * @param layout Square | Tall | Wide (optional, default to "")
     * @param license Any | Public | Share | ShareCommercially | Modify (optional, default to "")
     * @return RequestConfig
     */
    fun duckduckgoImageSearchRequestConfig(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, page: kotlin.Int?, size: kotlin.String?, color: kotlin.String?, imageType: kotlin.String?, layout: kotlin.String?, license: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (region != null) {
                    put("region", listOf(region.toString()))
                }
                if (safesearch != null) {
                    put("safesearch", listOf(safesearch.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
                if (color != null) {
                    put("color", listOf(color.toString()))
                }
                if (imageType != null) {
                    put("image_type", listOf(imageType.toString()))
                }
                if (layout != null) {
                    put("layout", listOf(layout.toString()))
                }
                if (license != null) {
                    put("license", listOf(license.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/images",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Instant Answer
     * DuckDuckGo Instant Answer — abstract, definition, direct answer, related topics.
     * @param query Query for the Instant Answer API
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoInstantAnswer(query: kotlin.String) : kotlin.Any {
        val localVarResponse = duckduckgoInstantAnswerWithHttpInfo(query = query)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Instant Answer
     * DuckDuckGo Instant Answer — abstract, definition, direct answer, related topics.
     * @param query Query for the Instant Answer API
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoInstantAnswerWithHttpInfo(query: kotlin.String) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoInstantAnswerRequestConfig(query = query)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoInstantAnswer
     *
     * @param query Query for the Instant Answer API
     * @return RequestConfig
     */
    fun duckduckgoInstantAnswerRequestConfig(query: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/instant",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List supported regions
     * The full DuckDuckGo region (kl) code list.
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoListSupportedRegions() : kotlin.Any {
        val localVarResponse = duckduckgoListSupportedRegionsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List supported regions
     * The full DuckDuckGo region (kl) code list.
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoListSupportedRegionsWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoListSupportedRegionsRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoListSupportedRegions
     *
     * @return RequestConfig
     */
    fun duckduckgoListSupportedRegionsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/regions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * News search
     * DuckDuckGo news search — headline, source, excerpt, unix + ISO date, image.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param timelimit day | week | month | year (optional, default to "")
     * @param page 30 results per page (optional, default to 1)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoNewsSearch(query: kotlin.String, region: kotlin.String? = "wt-wt", safesearch: kotlin.String? = "moderate", timelimit: kotlin.String? = "", page: kotlin.Int? = 1) : kotlin.Any {
        val localVarResponse = duckduckgoNewsSearchWithHttpInfo(query = query, region = region, safesearch = safesearch, timelimit = timelimit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * News search
     * DuckDuckGo news search — headline, source, excerpt, unix + ISO date, image.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param timelimit day | week | month | year (optional, default to "")
     * @param page 30 results per page (optional, default to 1)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoNewsSearchWithHttpInfo(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, timelimit: kotlin.String?, page: kotlin.Int?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoNewsSearchRequestConfig(query = query, region = region, safesearch = safesearch, timelimit = timelimit, page = page)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoNewsSearch
     *
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param timelimit day | week | month | year (optional, default to "")
     * @param page 30 results per page (optional, default to 1)
     * @return RequestConfig
     */
    fun duckduckgoNewsSearchRequestConfig(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, timelimit: kotlin.String?, page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (region != null) {
                    put("region", listOf(region.toString()))
                }
                if (safesearch != null) {
                    put("safesearch", listOf(safesearch.toString()))
                }
                if (timelimit != null) {
                    put("timelimit", listOf(timelimit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/news",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search suggestions
     * DuckDuckGo search-box suggestions.
     * @param query Partial query to complete
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoSearchSuggestions(query: kotlin.String, region: kotlin.String? = "wt-wt") : kotlin.Any {
        val localVarResponse = duckduckgoSearchSuggestionsWithHttpInfo(query = query, region = region)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search suggestions
     * DuckDuckGo search-box suggestions.
     * @param query Partial query to complete
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoSearchSuggestionsWithHttpInfo(query: kotlin.String, region: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoSearchSuggestionsRequestConfig(query = query, region = region)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoSearchSuggestions
     *
     * @param query Partial query to complete
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @return RequestConfig
     */
    fun duckduckgoSearchSuggestionsRequestConfig(query: kotlin.String, region: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (region != null) {
                    put("region", listOf(region.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/autocomplete",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Video search
     * DuckDuckGo video search — title, publisher, uploader, duration, views, thumbnails.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param page 60 results per page (optional, default to 1)
     * @param duration short | medium | long (optional, default to "")
     * @param resolution high | standard (optional, default to "")
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoVideoSearch(query: kotlin.String, region: kotlin.String? = "wt-wt", safesearch: kotlin.String? = "moderate", page: kotlin.Int? = 1, duration: kotlin.String? = "", resolution: kotlin.String? = "") : kotlin.Any {
        val localVarResponse = duckduckgoVideoSearchWithHttpInfo(query = query, region = region, safesearch = safesearch, page = page, duration = duration, resolution = resolution)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Video search
     * DuckDuckGo video search — title, publisher, uploader, duration, views, thumbnails.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param page 60 results per page (optional, default to 1)
     * @param duration short | medium | long (optional, default to "")
     * @param resolution high | standard (optional, default to "")
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoVideoSearchWithHttpInfo(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, page: kotlin.Int?, duration: kotlin.String?, resolution: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoVideoSearchRequestConfig(query = query, region = region, safesearch = safesearch, page = page, duration = duration, resolution = resolution)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoVideoSearch
     *
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param page 60 results per page (optional, default to 1)
     * @param duration short | medium | long (optional, default to "")
     * @param resolution high | standard (optional, default to "")
     * @return RequestConfig
     */
    fun duckduckgoVideoSearchRequestConfig(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, page: kotlin.Int?, duration: kotlin.String?, resolution: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (region != null) {
                    put("region", listOf(region.toString()))
                }
                if (safesearch != null) {
                    put("safesearch", listOf(safesearch.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (duration != null) {
                    put("duration", listOf(duration.toString()))
                }
                if (resolution != null) {
                    put("resolution", listOf(resolution.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/videos",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Web search
     * DuckDuckGo web SERP — organic results, the zero-click abstract box, ads flagged.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param timelimit day | week | month | year (optional, default to "")
     * @param page  (optional, default to 1)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun duckduckgoWebSearch(query: kotlin.String, region: kotlin.String? = "wt-wt", safesearch: kotlin.String? = "moderate", timelimit: kotlin.String? = "", page: kotlin.Int? = 1) : kotlin.Any {
        val localVarResponse = duckduckgoWebSearchWithHttpInfo(query = query, region = region, safesearch = safesearch, timelimit = timelimit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Web search
     * DuckDuckGo web SERP — organic results, the zero-click abstract box, ads flagged.
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param timelimit day | week | month | year (optional, default to "")
     * @param page  (optional, default to 1)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun duckduckgoWebSearchWithHttpInfo(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, timelimit: kotlin.String?, page: kotlin.Int?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = duckduckgoWebSearchRequestConfig(query = query, region = region, safesearch = safesearch, timelimit = timelimit, page = page)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation duckduckgoWebSearch
     *
     * @param query Search query
     * @param region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions. (optional, default to "wt-wt")
     * @param safesearch on | moderate | off (optional, default to "moderate")
     * @param timelimit day | week | month | year (optional, default to "")
     * @param page  (optional, default to 1)
     * @return RequestConfig
     */
    fun duckduckgoWebSearchRequestConfig(query: kotlin.String, region: kotlin.String?, safesearch: kotlin.String?, timelimit: kotlin.String?, page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (region != null) {
                    put("region", listOf(region.toString()))
                }
                if (safesearch != null) {
                    put("safesearch", listOf(safesearch.toString()))
                }
                if (timelimit != null) {
                    put("timelimit", listOf(timelimit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/duckduckgo/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
