/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.scrapebadger.client.models.HTTPValidationError

import com.squareup.moshi.Json

import com.scrapebadger.client.infrastructure.ApiClient
import com.scrapebadger.client.infrastructure.ApiResponse
import com.scrapebadger.client.infrastructure.ClientException
import com.scrapebadger.client.infrastructure.ClientError
import com.scrapebadger.client.infrastructure.ServerException
import com.scrapebadger.client.infrastructure.ServerError
import com.scrapebadger.client.infrastructure.MultiValueMap
import com.scrapebadger.client.infrastructure.PartConfig
import com.scrapebadger.client.infrastructure.RequestConfig
import com.scrapebadger.client.infrastructure.RequestMethod
import com.scrapebadger.client.infrastructure.ResponseType
import com.scrapebadger.client.infrastructure.Success
import com.scrapebadger.client.infrastructure.toMultiValue

class EBayApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://scrapebadger.com")
        }
    }

    /**
     * Browse a category
     * List active listings within an eBay category.
     * @param categoryId 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @param perPage  (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayBrowseACategory(categoryId: kotlin.String, domain: kotlin.String? = "com", page: kotlin.Int? = 1, perPage: kotlin.Int? = null, sortBy: kotlin.String? = "best_match", minPrice: java.math.BigDecimal? = null, maxPrice: java.math.BigDecimal? = null) : kotlin.Any {
        val localVarResponse = ebayBrowseACategoryWithHttpInfo(categoryId = categoryId, domain = domain, page = page, perPage = perPage, sortBy = sortBy, minPrice = minPrice, maxPrice = maxPrice)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Browse a category
     * List active listings within an eBay category.
     * @param categoryId 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @param perPage  (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayBrowseACategoryWithHttpInfo(categoryId: kotlin.String, domain: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, sortBy: kotlin.String?, minPrice: java.math.BigDecimal?, maxPrice: java.math.BigDecimal?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayBrowseACategoryRequestConfig(categoryId = categoryId, domain = domain, page = page, perPage = perPage, sortBy = sortBy, minPrice = minPrice, maxPrice = maxPrice)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayBrowseACategory
     *
     * @param categoryId 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @param perPage  (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @return RequestConfig
     */
    fun ebayBrowseACategoryRequestConfig(categoryId: kotlin.String, domain: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, sortBy: kotlin.String?, minPrice: java.math.BigDecimal?, maxPrice: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (sortBy != null) {
                    put("sort_by", listOf(sortBy.toString()))
                }
                if (minPrice != null) {
                    put("min_price", listOf(minPrice.toString()))
                }
                if (maxPrice != null) {
                    put("max_price", listOf(maxPrice.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/categories/{category_id}/items".replace("{"+"category_id"+"}", encodeURIComponent(categoryId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Completed / sold listings
     * Search completed/sold listings — eBay&#39;s sold-price history.
     * @param query Search keywords
     * @param domain Marketplace domain (com, co.uk, de …) (optional, default to "com")
     * @param categoryId Restrict to a category id (optional)
     * @param page  (optional, default to 1)
     * @param perPage 60, 120 or 240 (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param condition new|open_box|refurbished|used|for_parts|graded|ungraded (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param location domestic|worldwide (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayCompletedSoldListings(query: kotlin.String, domain: kotlin.String? = "com", categoryId: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = null, sortBy: kotlin.String? = "best_match", condition: kotlin.String? = null, minPrice: java.math.BigDecimal? = null, maxPrice: java.math.BigDecimal? = null, location: kotlin.String? = null) : kotlin.Any {
        val localVarResponse = ebayCompletedSoldListingsWithHttpInfo(query = query, domain = domain, categoryId = categoryId, page = page, perPage = perPage, sortBy = sortBy, condition = condition, minPrice = minPrice, maxPrice = maxPrice, location = location)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Completed / sold listings
     * Search completed/sold listings — eBay&#39;s sold-price history.
     * @param query Search keywords
     * @param domain Marketplace domain (com, co.uk, de …) (optional, default to "com")
     * @param categoryId Restrict to a category id (optional)
     * @param page  (optional, default to 1)
     * @param perPage 60, 120 or 240 (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param condition new|open_box|refurbished|used|for_parts|graded|ungraded (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param location domestic|worldwide (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayCompletedSoldListingsWithHttpInfo(query: kotlin.String, domain: kotlin.String?, categoryId: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, sortBy: kotlin.String?, condition: kotlin.String?, minPrice: java.math.BigDecimal?, maxPrice: java.math.BigDecimal?, location: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayCompletedSoldListingsRequestConfig(query = query, domain = domain, categoryId = categoryId, page = page, perPage = perPage, sortBy = sortBy, condition = condition, minPrice = minPrice, maxPrice = maxPrice, location = location)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayCompletedSoldListings
     *
     * @param query Search keywords
     * @param domain Marketplace domain (com, co.uk, de …) (optional, default to "com")
     * @param categoryId Restrict to a category id (optional)
     * @param page  (optional, default to 1)
     * @param perPage 60, 120 or 240 (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param condition new|open_box|refurbished|used|for_parts|graded|ungraded (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param location domestic|worldwide (optional)
     * @return RequestConfig
     */
    fun ebayCompletedSoldListingsRequestConfig(query: kotlin.String, domain: kotlin.String?, categoryId: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, sortBy: kotlin.String?, condition: kotlin.String?, minPrice: java.math.BigDecimal?, maxPrice: java.math.BigDecimal?, location: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
                if (categoryId != null) {
                    put("category_id", listOf(categoryId.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (sortBy != null) {
                    put("sort_by", listOf(sortBy.toString()))
                }
                if (condition != null) {
                    put("condition", listOf(condition.toString()))
                }
                if (minPrice != null) {
                    put("min_price", listOf(minPrice.toString()))
                }
                if (maxPrice != null) {
                    put("max_price", listOf(maxPrice.toString()))
                }
                if (location != null) {
                    put("location", listOf(location.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/completed",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * eBay scraper health check
     * Check health of the eBay scraper service (accepts HEAD for UptimeRobot).
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayEbayScraperHealthCheck() : kotlin.Any {
        val localVarResponse = ebayEbayScraperHealthCheckWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * eBay scraper health check
     * Check health of the eBay scraper service (accepts HEAD for UptimeRobot).
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayEbayScraperHealthCheckWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayEbayScraperHealthCheckRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayEbayScraperHealthCheck
     *
     * @return RequestConfig
     */
    fun ebayEbayScraperHealthCheckRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * eBay scraper health check
     * Check health of the eBay scraper service (accepts HEAD for UptimeRobot).
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayEbayScraperHealthCheckHead() : kotlin.Any {
        val localVarResponse = ebayEbayScraperHealthCheckHeadWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * eBay scraper health check
     * Check health of the eBay scraper service (accepts HEAD for UptimeRobot).
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayEbayScraperHealthCheckHeadWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayEbayScraperHealthCheckHeadRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayEbayScraperHealthCheckHead
     *
     * @return RequestConfig
     */
    fun ebayEbayScraperHealthCheckHeadRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.HEAD,
            path = "/v1/ebay/health",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get item detail
     * Get a single eBay listing&#39;s full detail.
     * @param itemId 
     * @param domain  (optional, default to "com")
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayGetItemDetail(itemId: kotlin.String, domain: kotlin.String? = "com") : kotlin.Any {
        val localVarResponse = ebayGetItemDetailWithHttpInfo(itemId = itemId, domain = domain)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get item detail
     * Get a single eBay listing&#39;s full detail.
     * @param itemId 
     * @param domain  (optional, default to "com")
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayGetItemDetailWithHttpInfo(itemId: kotlin.String, domain: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayGetItemDetailRequestConfig(itemId = itemId, domain = domain)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayGetItemDetail
     *
     * @param itemId 
     * @param domain  (optional, default to "com")
     * @return RequestConfig
     */
    fun ebayGetItemDetailRequestConfig(itemId: kotlin.String, domain: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/items/{item_id}".replace("{"+"item_id"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get item reviews
     * Get catalog product reviews shown on an eBay listing.
     * @param itemId 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayGetItemReviews(itemId: kotlin.String, domain: kotlin.String? = "com", page: kotlin.Int? = 1) : kotlin.Any {
        val localVarResponse = ebayGetItemReviewsWithHttpInfo(itemId = itemId, domain = domain, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get item reviews
     * Get catalog product reviews shown on an eBay listing.
     * @param itemId 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayGetItemReviewsWithHttpInfo(itemId: kotlin.String, domain: kotlin.String?, page: kotlin.Int?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayGetItemReviewsRequestConfig(itemId = itemId, domain = domain, page = page)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayGetItemReviews
     *
     * @param itemId 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @return RequestConfig
     */
    fun ebayGetItemReviewsRequestConfig(itemId: kotlin.String, domain: kotlin.String?, page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/items/{item_id}/reviews".replace("{"+"item_id"+"}", encodeURIComponent(itemId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get seller feedback
     * Get a seller&#39;s recent feedback comments.
     * @param username 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayGetSellerFeedback(username: kotlin.String, domain: kotlin.String? = "com", page: kotlin.Int? = 1) : kotlin.Any {
        val localVarResponse = ebayGetSellerFeedbackWithHttpInfo(username = username, domain = domain, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get seller feedback
     * Get a seller&#39;s recent feedback comments.
     * @param username 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayGetSellerFeedbackWithHttpInfo(username: kotlin.String, domain: kotlin.String?, page: kotlin.Int?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayGetSellerFeedbackRequestConfig(username = username, domain = domain, page = page)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayGetSellerFeedback
     *
     * @param username 
     * @param domain  (optional, default to "com")
     * @param page  (optional, default to 1)
     * @return RequestConfig
     */
    fun ebayGetSellerFeedbackRequestConfig(username: kotlin.String, domain: kotlin.String?, page: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/sellers/{username}/feedback".replace("{"+"username"+"}", encodeURIComponent(username.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get seller listings
     * List the active listings of a single eBay seller.
     * @param username 
     * @param domain  (optional, default to "com")
     * @param query  (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayGetSellerListings(username: kotlin.String, domain: kotlin.String? = "com", query: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = null) : kotlin.Any {
        val localVarResponse = ebayGetSellerListingsWithHttpInfo(username = username, domain = domain, query = query, page = page, perPage = perPage)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get seller listings
     * List the active listings of a single eBay seller.
     * @param username 
     * @param domain  (optional, default to "com")
     * @param query  (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayGetSellerListingsWithHttpInfo(username: kotlin.String, domain: kotlin.String?, query: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayGetSellerListingsRequestConfig(username = username, domain = domain, query = query, page = page, perPage = perPage)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayGetSellerListings
     *
     * @param username 
     * @param domain  (optional, default to "com")
     * @param query  (optional)
     * @param page  (optional, default to 1)
     * @param perPage  (optional)
     * @return RequestConfig
     */
    fun ebayGetSellerListingsRequestConfig(username: kotlin.String, domain: kotlin.String?, query: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
                if (query != null) {
                    put("query", listOf(query.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/sellers/{username}/items".replace("{"+"username"+"}", encodeURIComponent(username.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get seller profile
     * Get an eBay seller&#39;s public profile.
     * @param username 
     * @param domain  (optional, default to "com")
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayGetSellerProfile(username: kotlin.String, domain: kotlin.String? = "com") : kotlin.Any {
        val localVarResponse = ebayGetSellerProfileWithHttpInfo(username = username, domain = domain)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get seller profile
     * Get an eBay seller&#39;s public profile.
     * @param username 
     * @param domain  (optional, default to "com")
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayGetSellerProfileWithHttpInfo(username: kotlin.String, domain: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayGetSellerProfileRequestConfig(username = username, domain = domain)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayGetSellerProfile
     *
     * @param username 
     * @param domain  (optional, default to "com")
     * @return RequestConfig
     */
    fun ebayGetSellerProfileRequestConfig(username: kotlin.String, domain: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/sellers/{username}".replace("{"+"username"+"}", encodeURIComponent(username.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Keyword suggestions
     * Return eBay keyword autocomplete suggestions.
     * @param query Partial query prefix
     * @param domain  (optional, default to "com")
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayKeywordSuggestions(query: kotlin.String, domain: kotlin.String? = "com") : kotlin.Any {
        val localVarResponse = ebayKeywordSuggestionsWithHttpInfo(query = query, domain = domain)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Keyword suggestions
     * Return eBay keyword autocomplete suggestions.
     * @param query Partial query prefix
     * @param domain  (optional, default to "com")
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayKeywordSuggestionsWithHttpInfo(query: kotlin.String, domain: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayKeywordSuggestionsRequestConfig(query = query, domain = domain)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayKeywordSuggestions
     *
     * @param query Partial query prefix
     * @param domain  (optional, default to "com")
     * @return RequestConfig
     */
    fun ebayKeywordSuggestionsRequestConfig(query: kotlin.String, domain: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/autocomplete",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List categories
     * List eBay&#39;s top-level category ids.
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayListCategories() : kotlin.Any {
        val localVarResponse = ebayListCategoriesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List categories
     * List eBay&#39;s top-level category ids.
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayListCategoriesWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayListCategoriesRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayListCategories
     *
     * @return RequestConfig
     */
    fun ebayListCategoriesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/categories",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List markets
     * List all supported eBay marketplaces.
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebayListMarkets() : kotlin.Any {
        val localVarResponse = ebayListMarketsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List markets
     * List all supported eBay marketplaces.
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebayListMarketsWithHttpInfo() : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebayListMarketsRequestConfig()

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebayListMarkets
     *
     * @return RequestConfig
     */
    fun ebayListMarketsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/markets",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Search listings
     * Search an eBay marketplace for active listings.
     * @param query Search keywords
     * @param domain Marketplace domain (com, co.uk, de …) (optional, default to "com")
     * @param categoryId Restrict to a category id (optional)
     * @param page  (optional, default to 1)
     * @param perPage 60, 120 or 240 (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param condition new|open_box|refurbished|used|for_parts|graded|ungraded (optional)
     * @param buyingFormat auction|buy_it_now|best_offer (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param freeShipping  (optional, default to false)
     * @param location domestic|worldwide (optional)
     * @return kotlin.Any
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun ebaySearchListings(query: kotlin.String, domain: kotlin.String? = "com", categoryId: kotlin.String? = null, page: kotlin.Int? = 1, perPage: kotlin.Int? = null, sortBy: kotlin.String? = "best_match", condition: kotlin.String? = null, buyingFormat: kotlin.String? = null, minPrice: java.math.BigDecimal? = null, maxPrice: java.math.BigDecimal? = null, freeShipping: kotlin.Boolean? = false, location: kotlin.String? = null) : kotlin.Any {
        val localVarResponse = ebaySearchListingsWithHttpInfo(query = query, domain = domain, categoryId = categoryId, page = page, perPage = perPage, sortBy = sortBy, condition = condition, buyingFormat = buyingFormat, minPrice = minPrice, maxPrice = maxPrice, freeShipping = freeShipping, location = location)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.Any
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Search listings
     * Search an eBay marketplace for active listings.
     * @param query Search keywords
     * @param domain Marketplace domain (com, co.uk, de …) (optional, default to "com")
     * @param categoryId Restrict to a category id (optional)
     * @param page  (optional, default to 1)
     * @param perPage 60, 120 or 240 (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param condition new|open_box|refurbished|used|for_parts|graded|ungraded (optional)
     * @param buyingFormat auction|buy_it_now|best_offer (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param freeShipping  (optional, default to false)
     * @param location domestic|worldwide (optional)
     * @return ApiResponse<kotlin.Any?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun ebaySearchListingsWithHttpInfo(query: kotlin.String, domain: kotlin.String?, categoryId: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, sortBy: kotlin.String?, condition: kotlin.String?, buyingFormat: kotlin.String?, minPrice: java.math.BigDecimal?, maxPrice: java.math.BigDecimal?, freeShipping: kotlin.Boolean?, location: kotlin.String?) : ApiResponse<kotlin.Any?> {
        val localVariableConfig = ebaySearchListingsRequestConfig(query = query, domain = domain, categoryId = categoryId, page = page, perPage = perPage, sortBy = sortBy, condition = condition, buyingFormat = buyingFormat, minPrice = minPrice, maxPrice = maxPrice, freeShipping = freeShipping, location = location)

        return request<Unit, kotlin.Any>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation ebaySearchListings
     *
     * @param query Search keywords
     * @param domain Marketplace domain (com, co.uk, de …) (optional, default to "com")
     * @param categoryId Restrict to a category id (optional)
     * @param page  (optional, default to 1)
     * @param perPage 60, 120 or 240 (optional)
     * @param sortBy best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low (optional, default to "best_match")
     * @param condition new|open_box|refurbished|used|for_parts|graded|ungraded (optional)
     * @param buyingFormat auction|buy_it_now|best_offer (optional)
     * @param minPrice  (optional)
     * @param maxPrice  (optional)
     * @param freeShipping  (optional, default to false)
     * @param location domestic|worldwide (optional)
     * @return RequestConfig
     */
    fun ebaySearchListingsRequestConfig(query: kotlin.String, domain: kotlin.String?, categoryId: kotlin.String?, page: kotlin.Int?, perPage: kotlin.Int?, sortBy: kotlin.String?, condition: kotlin.String?, buyingFormat: kotlin.String?, minPrice: java.math.BigDecimal?, maxPrice: java.math.BigDecimal?, freeShipping: kotlin.Boolean?, location: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("query", listOf(query.toString()))
                if (domain != null) {
                    put("domain", listOf(domain.toString()))
                }
                if (categoryId != null) {
                    put("category_id", listOf(categoryId.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (perPage != null) {
                    put("per_page", listOf(perPage.toString()))
                }
                if (sortBy != null) {
                    put("sort_by", listOf(sortBy.toString()))
                }
                if (condition != null) {
                    put("condition", listOf(condition.toString()))
                }
                if (buyingFormat != null) {
                    put("buying_format", listOf(buyingFormat.toString()))
                }
                if (minPrice != null) {
                    put("min_price", listOf(minPrice.toString()))
                }
                if (maxPrice != null) {
                    put("max_price", listOf(maxPrice.toString()))
                }
                if (freeShipping != null) {
                    put("free_shipping", listOf(freeShipping.toString()))
                }
                if (location != null) {
                    put("location", listOf(location.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/ebay/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
