/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Billing activity log entry.
 *
 * @param id 
 * @param monitorId 
 * @param monitorName 
 * @param billedAt 
 * @param numAccounts 
 * @param creditsDeducted 
 * @param tierLabel 
 * @param rateApplied 
 */


data class BillingLogResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "monitor_id")
    val monitorId: kotlin.String,

    @Json(name = "monitor_name")
    val monitorName: kotlin.String,

    @Json(name = "billed_at")
    val billedAt: java.time.OffsetDateTime,

    @Json(name = "num_accounts")
    val numAccounts: kotlin.Int,

    @Json(name = "credits_deducted")
    val creditsDeducted: java.math.BigDecimal,

    @Json(name = "tier_label")
    val tierLabel: kotlin.String,

    @Json(name = "rate_applied")
    val rateApplied: java.math.BigDecimal

) {


}

