/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import com.scrapebadger.client.models.FilterRuleResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Paginated list of filter rules.
 *
 * @param rules 
 * @param total 
 * @param page 
 * @param pageSize 
 */


data class FilterRuleListResponse (

    @Json(name = "rules")
    val rules: kotlin.collections.List<FilterRuleResponse>,

    @Json(name = "total")
    val total: kotlin.Int,

    @Json(name = "page")
    val page: kotlin.Int,

    @Json(name = "page_size")
    val pageSize: kotlin.Int

) {


}

