/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Filter rule response.  Per-poll billing — see ``GET /v1/twitter/filter-rules/pricing`` for the rates that apply globally to every rule.
 *
 * @param id 
 * @param tag 
 * @param query 
 * @param intervalSeconds 
 * @param maxResultsPerPoll 
 * @param status 
 * @param statusReason 
 * @param webhookUrl 
 * @param webhookSecretSet 
 * @param totalCreditsBurned 
 * @param createdAt 
 * @param updatedAt 
 */


data class FilterRuleResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "tag")
    val tag: kotlin.String,

    @Json(name = "query")
    val query: kotlin.String,

    @Json(name = "interval_seconds")
    val intervalSeconds: java.math.BigDecimal,

    @Json(name = "max_results_per_poll")
    val maxResultsPerPoll: kotlin.Int,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "status_reason")
    val statusReason: kotlin.String?,

    @Json(name = "webhook_url")
    val webhookUrl: kotlin.String?,

    @Json(name = "webhook_secret_set")
    val webhookSecretSet: kotlin.Boolean,

    @Json(name = "total_credits_burned")
    val totalCreditsBurned: java.math.BigDecimal,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

