/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Validation result for a Twitter search query.
 *
 * @param valid 
 * @param query 
 * @param error 
 */


data class FilterRuleValidateResponse (

    @Json(name = "valid")
    val valid: kotlin.Boolean,

    @Json(name = "query")
    val query: kotlin.String,

    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

