/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models

import com.scrapebadger.client.models.VintedItemDetail

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Envelope returned by item detail.
 *
 * @param item 
 * @param market 
 */


data class ItemDetailResponse (

    @Json(name = "item")
    val item: VintedItemDetail,

    @Json(name = "market")
    val market: kotlin.String

) {


}

