/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Active subscription details (null when PAYG-only).
 *
 * @param planCode 
 * @param planTitle 
 * @param billingCadence 
 * @param status 
 * @param currentPeriodStart 
 * @param currentPeriodEnd 
 * @param cancelAtPeriodEnd 
 * @param cancelEffectiveAt 
 * @param monthlyCredits 
 * @param pendingPlanCode 
 * @param pendingPlanTitle 
 * @param pendingChangeEffectiveAt 
 */


data class SubscriptionInfo (

    @Json(name = "plan_code")
    val planCode: kotlin.String,

    @Json(name = "plan_title")
    val planTitle: kotlin.String,

    @Json(name = "billing_cadence")
    val billingCadence: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "current_period_start")
    val currentPeriodStart: java.time.OffsetDateTime? = null,

    @Json(name = "current_period_end")
    val currentPeriodEnd: java.time.OffsetDateTime? = null,

    @Json(name = "cancel_at_period_end")
    val cancelAtPeriodEnd: kotlin.Boolean? = false,

    @Json(name = "cancel_effective_at")
    val cancelEffectiveAt: java.time.OffsetDateTime? = null,

    @Json(name = "monthly_credits")
    val monthlyCredits: kotlin.Int? = 0,

    @Json(name = "pending_plan_code")
    val pendingPlanCode: kotlin.String? = null,

    @Json(name = "pending_plan_title")
    val pendingPlanTitle: kotlin.String? = null,

    @Json(name = "pending_change_effective_at")
    val pendingChangeEffectiveAt: java.time.OffsetDateTime? = null

) {


}

