/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Parameters are validated against the discoverable operation catalog.
 *
 * @param market Vinted market code; uk aliases gb
 * @param parameters Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples.
 */


data class VintedMobileReadRequest (

    /* Vinted market code; uk aliases gb */
    @Json(name = "market")
    val market: kotlin.String? = "fr",

    /* Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples. */
    @Json(name = "parameters")
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

