/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A brand, as the brand search returns it.
 *
 * @param id 
 * @param title 
 * @param slug 
 * @param itemCount 
 * @param favouriteCount 
 * @param isLuxury 
 * @param url 
 */


data class VintedBrand (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "slug")
    val slug: kotlin.String,

    @Json(name = "item_count")
    val itemCount: kotlin.Int? = 0,

    @Json(name = "favourite_count")
    val favouriteCount: kotlin.Int? = 0,

    @Json(name = "is_luxury")
    val isLuxury: kotlin.Boolean? = false,

    @Json(name = "url")
    val url: kotlin.String? = null

) {


}

