/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.DuckDuckGoApi
import com.scrapebadger.client.models.HTTPValidationError

class DuckDuckGoApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DuckDuckGoApi
        //val apiInstance = DuckDuckGoApi()

        // to test duckduckgoDuckduckgoScraperHealthCheck
        should("test duckduckgoDuckduckgoScraperHealthCheck") {
            // uncomment below to test duckduckgoDuckduckgoScraperHealthCheck
            //val result : kotlin.Any = apiInstance.duckduckgoDuckduckgoScraperHealthCheck()
            //result shouldBe ("TODO")
        }

        // to test duckduckgoDuckduckgoScraperHealthCheckHead
        should("test duckduckgoDuckduckgoScraperHealthCheckHead") {
            // uncomment below to test duckduckgoDuckduckgoScraperHealthCheckHead
            //val result : kotlin.Any = apiInstance.duckduckgoDuckduckgoScraperHealthCheckHead()
            //result shouldBe ("TODO")
        }

        // to test duckduckgoImageSearch
        should("test duckduckgoImageSearch") {
            // uncomment below to test duckduckgoImageSearch
            //val query : kotlin.String = query_example // kotlin.String | Search query
            //val region : kotlin.String = region_example // kotlin.String | DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt = all regions.
            //val safesearch : kotlin.String = safesearch_example // kotlin.String | on | moderate | off
            //val page : kotlin.Int = 56 // kotlin.Int | 100 results per page
            //val size : kotlin.String = size_example // kotlin.String | Small | Medium | Large | Wallpaper
            //val color : kotlin.String = color_example // kotlin.String | color | Monochrome | Red | Blue | …
            //val imageType : kotlin.String = imageType_example // kotlin.String | photo | clipart | gif | transparent | line
            //val layout : kotlin.String = layout_example // kotlin.String | Square | Tall | Wide
            //val license : kotlin.String = license_example // kotlin.String | Any | Public | Share | ShareCommercially | Modify
            //val result : kotlin.Any = apiInstance.duckduckgoImageSearch(query, region, safesearch, page, size, color, imageType, layout, license)
            //result shouldBe ("TODO")
        }

        // to test duckduckgoInstantAnswer
        should("test duckduckgoInstantAnswer") {
            // uncomment below to test duckduckgoInstantAnswer
            //val query : kotlin.String = query_example // kotlin.String | Query for the Instant Answer API
            //val result : kotlin.Any = apiInstance.duckduckgoInstantAnswer(query)
            //result shouldBe ("TODO")
        }

        // to test duckduckgoListSupportedRegions
        should("test duckduckgoListSupportedRegions") {
            // uncomment below to test duckduckgoListSupportedRegions
            //val result : kotlin.Any = apiInstance.duckduckgoListSupportedRegions()
            //result shouldBe ("TODO")
        }

        // to test duckduckgoNewsSearch
        should("test duckduckgoNewsSearch") {
            // uncomment below to test duckduckgoNewsSearch
            //val query : kotlin.String = query_example // kotlin.String | Search query
            //val region : kotlin.String = region_example // kotlin.String | DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt = all regions.
            //val safesearch : kotlin.String = safesearch_example // kotlin.String | on | moderate | off
            //val timelimit : kotlin.String = timelimit_example // kotlin.String | day | week | month | year
            //val page : kotlin.Int = 56 // kotlin.Int | 30 results per page
            //val result : kotlin.Any = apiInstance.duckduckgoNewsSearch(query, region, safesearch, timelimit, page)
            //result shouldBe ("TODO")
        }

        // to test duckduckgoSearchSuggestions
        should("test duckduckgoSearchSuggestions") {
            // uncomment below to test duckduckgoSearchSuggestions
            //val query : kotlin.String = query_example // kotlin.String | Partial query to complete
            //val region : kotlin.String = region_example // kotlin.String | DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt = all regions.
            //val result : kotlin.Any = apiInstance.duckduckgoSearchSuggestions(query, region)
            //result shouldBe ("TODO")
        }

        // to test duckduckgoVideoSearch
        should("test duckduckgoVideoSearch") {
            // uncomment below to test duckduckgoVideoSearch
            //val query : kotlin.String = query_example // kotlin.String | Search query
            //val region : kotlin.String = region_example // kotlin.String | DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt = all regions.
            //val safesearch : kotlin.String = safesearch_example // kotlin.String | on | moderate | off
            //val page : kotlin.Int = 56 // kotlin.Int | 60 results per page
            //val duration : kotlin.String = duration_example // kotlin.String | short | medium | long
            //val resolution : kotlin.String = resolution_example // kotlin.String | high | standard
            //val result : kotlin.Any = apiInstance.duckduckgoVideoSearch(query, region, safesearch, page, duration, resolution)
            //result shouldBe ("TODO")
        }

        // to test duckduckgoWebSearch
        should("test duckduckgoWebSearch") {
            // uncomment below to test duckduckgoWebSearch
            //val query : kotlin.String = query_example // kotlin.String | Search query
            //val region : kotlin.String = region_example // kotlin.String | DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt = all regions.
            //val safesearch : kotlin.String = safesearch_example // kotlin.String | on | moderate | off
            //val timelimit : kotlin.String = timelimit_example // kotlin.String | day | week | month | year
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.duckduckgoWebSearch(query, region, safesearch, timelimit, page)
            //result shouldBe ("TODO")
        }

    }
}
