/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.EBayApi
import com.scrapebadger.client.models.HTTPValidationError

class EBayApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EBayApi
        //val apiInstance = EBayApi()

        // to test ebayBrowseACategory
        should("test ebayBrowseACategory") {
            // uncomment below to test ebayBrowseACategory
            //val categoryId : kotlin.String = categoryId_example // kotlin.String | 
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
            //val minPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val maxPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : kotlin.Any = apiInstance.ebayBrowseACategory(categoryId, domain, page, perPage, sortBy, minPrice, maxPrice)
            //result shouldBe ("TODO")
        }

        // to test ebayCompletedSoldListings
        should("test ebayCompletedSoldListings") {
            // uncomment below to test ebayCompletedSoldListings
            //val query : kotlin.String = query_example // kotlin.String | Search keywords
            //val domain : kotlin.String = domain_example // kotlin.String | Marketplace domain (com, co.uk, de …)
            //val categoryId : kotlin.String = categoryId_example // kotlin.String | Restrict to a category id
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 60, 120 or 240
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
            //val condition : kotlin.String = condition_example // kotlin.String | new|open_box|refurbished|used|for_parts
            //val minPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val maxPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : kotlin.Any = apiInstance.ebayCompletedSoldListings(query, domain, categoryId, page, perPage, sortBy, condition, minPrice, maxPrice)
            //result shouldBe ("TODO")
        }

        // to test ebayEbayScraperHealthCheck
        should("test ebayEbayScraperHealthCheck") {
            // uncomment below to test ebayEbayScraperHealthCheck
            //val result : kotlin.Any = apiInstance.ebayEbayScraperHealthCheck()
            //result shouldBe ("TODO")
        }

        // to test ebayEbayScraperHealthCheckHead
        should("test ebayEbayScraperHealthCheckHead") {
            // uncomment below to test ebayEbayScraperHealthCheckHead
            //val result : kotlin.Any = apiInstance.ebayEbayScraperHealthCheckHead()
            //result shouldBe ("TODO")
        }

        // to test ebayGetItemDetail
        should("test ebayGetItemDetail") {
            // uncomment below to test ebayGetItemDetail
            //val itemId : kotlin.String = itemId_example // kotlin.String | 
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.ebayGetItemDetail(itemId, domain)
            //result shouldBe ("TODO")
        }

        // to test ebayGetItemReviews
        should("test ebayGetItemReviews") {
            // uncomment below to test ebayGetItemReviews
            //val itemId : kotlin.String = itemId_example // kotlin.String | 
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.ebayGetItemReviews(itemId, domain, page)
            //result shouldBe ("TODO")
        }

        // to test ebayGetSellerFeedback
        should("test ebayGetSellerFeedback") {
            // uncomment below to test ebayGetSellerFeedback
            //val username : kotlin.String = username_example // kotlin.String | 
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.ebayGetSellerFeedback(username, domain, page)
            //result shouldBe ("TODO")
        }

        // to test ebayGetSellerListings
        should("test ebayGetSellerListings") {
            // uncomment below to test ebayGetSellerListings
            //val username : kotlin.String = username_example // kotlin.String | 
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val query : kotlin.String = query_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.ebayGetSellerListings(username, domain, query, page, perPage)
            //result shouldBe ("TODO")
        }

        // to test ebayGetSellerProfile
        should("test ebayGetSellerProfile") {
            // uncomment below to test ebayGetSellerProfile
            //val username : kotlin.String = username_example // kotlin.String | 
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.ebayGetSellerProfile(username, domain)
            //result shouldBe ("TODO")
        }

        // to test ebayKeywordSuggestions
        should("test ebayKeywordSuggestions") {
            // uncomment below to test ebayKeywordSuggestions
            //val query : kotlin.String = query_example // kotlin.String | Partial query prefix
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.ebayKeywordSuggestions(query, domain)
            //result shouldBe ("TODO")
        }

        // to test ebayListCategories
        should("test ebayListCategories") {
            // uncomment below to test ebayListCategories
            //val result : kotlin.Any = apiInstance.ebayListCategories()
            //result shouldBe ("TODO")
        }

        // to test ebayListMarkets
        should("test ebayListMarkets") {
            // uncomment below to test ebayListMarkets
            //val result : kotlin.Any = apiInstance.ebayListMarkets()
            //result shouldBe ("TODO")
        }

        // to test ebaySearchListings
        should("test ebaySearchListings") {
            // uncomment below to test ebaySearchListings
            //val query : kotlin.String = query_example // kotlin.String | Search keywords
            //val domain : kotlin.String = domain_example // kotlin.String | Marketplace domain (com, co.uk, de …)
            //val categoryId : kotlin.String = categoryId_example // kotlin.String | Restrict to a category id
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val perPage : kotlin.Int = 56 // kotlin.Int | 60, 120 or 240
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
            //val condition : kotlin.String = condition_example // kotlin.String | new|open_box|refurbished|used|for_parts
            //val buyingFormat : kotlin.String = buyingFormat_example // kotlin.String | auction|buy_it_now|best_offer
            //val minPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val maxPrice : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val freeShipping : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.Any = apiInstance.ebaySearchListings(query, domain, categoryId, page, perPage, sortBy, condition, buyingFormat, minPrice, maxPrice, freeShipping)
            //result shouldBe ("TODO")
        }

    }
}
