/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.FacebookApi
import com.scrapebadger.client.models.HTTPValidationError

class FacebookApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FacebookApi
        //val apiInstance = FacebookApi()

        // to test facebookBrowseAMarketplaceCategory
        should("test facebookBrowseAMarketplaceCategory") {
            // uncomment below to test facebookBrowseAMarketplaceCategory
            //val category : kotlin.String = category_example // kotlin.String | 
            //val location : kotlin.String = location_example // kotlin.String | 
            //val minPrice : kotlin.Int = 56 // kotlin.Int | 
            //val maxPrice : kotlin.Int = 56 // kotlin.Int | 
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookBrowseAMarketplaceCategory(category, location, minPrice, maxPrice, sortBy, after)
            //result shouldBe ("TODO")
        }

        // to test facebookGetAMarketplaceItem
        should("test facebookGetAMarketplaceItem") {
            // uncomment below to test facebookGetAMarketplaceItem
            //val itemId : kotlin.String = itemId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetAMarketplaceItem(itemId)
            //result shouldBe ("TODO")
        }

        // to test facebookGetAdvertiserPageInfo
        should("test facebookGetAdvertiserPageInfo") {
            // uncomment below to test facebookGetAdvertiserPageInfo
            //val pageId : kotlin.String = pageId_example // kotlin.String | 
            //val country : kotlin.String = country_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetAdvertiserPageInfo(pageId, country)
            //result shouldBe ("TODO")
        }

        // to test facebookGetAnAd
        should("test facebookGetAnAd") {
            // uncomment below to test facebookGetAnAd
            //val adArchiveId : kotlin.String = adArchiveId_example // kotlin.String | 
            //val country : kotlin.String = country_example // kotlin.String | ISO country code (an EU code returns EU transparency)
            //val result : kotlin.Any = apiInstance.facebookGetAnAd(adArchiveId, country)
            //result shouldBe ("TODO")
        }

        // to test facebookGetGroupDetail
        should("test facebookGetGroupDetail") {
            // uncomment below to test facebookGetGroupDetail
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetGroupDetail(groupId)
            //result shouldBe ("TODO")
        }

        // to test facebookGetGroupPosts
        should("test facebookGetGroupPosts") {
            // uncomment below to test facebookGetGroupPosts
            //val groupId : kotlin.String = groupId_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetGroupPosts(groupId, after)
            //result shouldBe ("TODO")
        }

        // to test facebookGetPageDetail
        should("test facebookGetPageDetail") {
            // uncomment below to test facebookGetPageDetail
            //val identifier : kotlin.String = identifier_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetPageDetail(identifier)
            //result shouldBe ("TODO")
        }

        // to test facebookGetPagePosts
        should("test facebookGetPagePosts") {
            // uncomment below to test facebookGetPagePosts
            //val identifier : kotlin.String = identifier_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetPagePosts(identifier, after)
            //result shouldBe ("TODO")
        }

        // to test facebookGetPostComments
        should("test facebookGetPostComments") {
            // uncomment below to test facebookGetPostComments
            //val postId : kotlin.String = postId_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetPostComments(postId, after, sort)
            //result shouldBe ("TODO")
        }

        // to test facebookGetPostDetail
        should("test facebookGetPostDetail") {
            // uncomment below to test facebookGetPostDetail
            //val postId : kotlin.String = postId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetPostDetail(postId)
            //result shouldBe ("TODO")
        }

        // to test facebookGetProfileDetail
        should("test facebookGetProfileDetail") {
            // uncomment below to test facebookGetProfileDetail
            //val identifier : kotlin.String = identifier_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetProfileDetail(identifier)
            //result shouldBe ("TODO")
        }

        // to test facebookGetProfilePosts
        should("test facebookGetProfilePosts") {
            // uncomment below to test facebookGetProfilePosts
            //val identifier : kotlin.String = identifier_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookGetProfilePosts(identifier, after)
            //result shouldBe ("TODO")
        }

        // to test facebookListCategories
        should("test facebookListCategories") {
            // uncomment below to test facebookListCategories
            //val result : kotlin.Any = apiInstance.facebookListCategories()
            //result shouldBe ("TODO")
        }

        // to test facebookListLocations
        should("test facebookListLocations") {
            // uncomment below to test facebookListLocations
            //val result : kotlin.Any = apiInstance.facebookListLocations()
            //result shouldBe ("TODO")
        }

        // to test facebookSearchAdvertiserPages
        should("test facebookSearchAdvertiserPages") {
            // uncomment below to test facebookSearchAdvertiserPages
            //val query : kotlin.String = query_example // kotlin.String | Advertiser name or keyword
            //val country : kotlin.String = country_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchAdvertiserPages(query, country)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchEvents
        should("test facebookSearchEvents") {
            // uncomment below to test facebookSearchEvents
            //val q : kotlin.String = q_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchEvents(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchEverything
        should("test facebookSearchEverything") {
            // uncomment below to test facebookSearchEverything
            //val q : kotlin.String = q_example // kotlin.String | Search query
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchEverything(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchGroups
        should("test facebookSearchGroups") {
            // uncomment below to test facebookSearchGroups
            //val q : kotlin.String = q_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchGroups(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchMarketplace
        should("test facebookSearchMarketplace") {
            // uncomment below to test facebookSearchMarketplace
            //val query : kotlin.String = query_example // kotlin.String | Search keywords
            //val location : kotlin.String = location_example // kotlin.String | Marketplace location slug
            //val minPrice : kotlin.Int = 56 // kotlin.Int | 
            //val maxPrice : kotlin.Int = 56 // kotlin.Int | 
            //val daysSinceListed : kotlin.Int = 56 // kotlin.Int | 
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | 
            //val itemCondition : kotlin.String = itemCondition_example // kotlin.String | 
            //val deliveryMethod : kotlin.String = deliveryMethod_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchMarketplace(query, location, minPrice, maxPrice, daysSinceListed, sortBy, itemCondition, deliveryMethod, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchPages
        should("test facebookSearchPages") {
            // uncomment below to test facebookSearchPages
            //val q : kotlin.String = q_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchPages(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchPeople
        should("test facebookSearchPeople") {
            // uncomment below to test facebookSearchPeople
            //val q : kotlin.String = q_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchPeople(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchPlaces
        should("test facebookSearchPlaces") {
            // uncomment below to test facebookSearchPlaces
            //val q : kotlin.String = q_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchPlaces(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchPosts
        should("test facebookSearchPosts") {
            // uncomment below to test facebookSearchPosts
            //val q : kotlin.String = q_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchPosts(q, after)
            //result shouldBe ("TODO")
        }

        // to test facebookSearchTheAdLibrary
        should("test facebookSearchTheAdLibrary") {
            // uncomment below to test facebookSearchTheAdLibrary
            //val query : kotlin.String = query_example // kotlin.String | Advertiser or keyword
            //val country : kotlin.String = country_example // kotlin.String | 
            //val adType : kotlin.String = adType_example // kotlin.String | 
            //val activeStatus : kotlin.String = activeStatus_example // kotlin.String | 
            //val after : kotlin.String = after_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.facebookSearchTheAdLibrary(query, country, adType, activeStatus, after)
            //result shouldBe ("TODO")
        }

    }
}
