/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.RealtorApi
import com.scrapebadger.client.models.HTTPValidationError

class RealtorApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RealtorApi
        //val apiInstance = RealtorApi()

        // to test realtorGetFullPropertyDetail
        should("test realtorGetFullPropertyDetail") {
            // uncomment below to test realtorGetFullPropertyDetail
            //val propertyId : kotlin.String = propertyId_example // kotlin.String | 
            //val market : kotlin.String = market_example // kotlin.String | us (realtor.com) | ca (realtor.ca)
            //val result : kotlin.Any = apiInstance.realtorGetFullPropertyDetail(propertyId, market)
            //result shouldBe ("TODO")
        }

        // to test realtorListMarkets
        should("test realtorListMarkets") {
            // uncomment below to test realtorListMarkets
            //val result : kotlin.Any = apiInstance.realtorListMarkets()
            //result shouldBe ("TODO")
        }

        // to test realtorLocationAutocomplete
        should("test realtorLocationAutocomplete") {
            // uncomment below to test realtorLocationAutocomplete
            //val query : kotlin.String = query_example // kotlin.String | Freetext location (city, ZIP/postal, address…)
            //val market : kotlin.String = market_example // kotlin.String | us (realtor.com) | ca (realtor.ca)
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.realtorLocationAutocomplete(query, market, limit)
            //result shouldBe ("TODO")
        }

        // to test realtorRealtorScraperHealthCheck
        should("test realtorRealtorScraperHealthCheck") {
            // uncomment below to test realtorRealtorScraperHealthCheck
            //val result : kotlin.Any = apiInstance.realtorRealtorScraperHealthCheck()
            //result shouldBe ("TODO")
        }

        // to test realtorRealtorScraperHealthCheckHead
        should("test realtorRealtorScraperHealthCheckHead") {
            // uncomment below to test realtorRealtorScraperHealthCheckHead
            //val result : kotlin.Any = apiInstance.realtorRealtorScraperHealthCheckHead()
            //result shouldBe ("TODO")
        }

        // to test realtorSearchPropertyListings
        should("test realtorSearchPropertyListings") {
            // uncomment below to test realtorSearchPropertyListings
            //val location : kotlin.String = location_example // kotlin.String | 'Austin, TX', a ZIP, 'Toronto, ON'…
            //val market : kotlin.String = market_example // kotlin.String | us (realtor.com) | ca (realtor.ca)
            //val status : kotlin.String = status_example // kotlin.String | for_sale | for_rent | sold | pending
            //val priceMin : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val priceMax : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val bedsMin : kotlin.Int = 56 // kotlin.Int | 
            //val bathsMin : kotlin.Int = 56 // kotlin.Int | 
            //val sqftMin : kotlin.Int = 56 // kotlin.Int | US only
            //val sqftMax : kotlin.Int = 56 // kotlin.Int | US only
            //val propertyType : kotlin.String = propertyType_example // kotlin.String | US only, CSV of property types
            //val sort : kotlin.String = sort_example // kotlin.String | relevant | newest | price_low | price_high | photo_count
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val latMin : java.math.BigDecimal = 8.14 // java.math.BigDecimal | CA bbox south
            //val latMax : java.math.BigDecimal = 8.14 // java.math.BigDecimal | CA bbox north
            //val lngMin : java.math.BigDecimal = 8.14 // java.math.BigDecimal | CA bbox west
            //val lngMax : java.math.BigDecimal = 8.14 // java.math.BigDecimal | CA bbox east
            //val result : kotlin.Any = apiInstance.realtorSearchPropertyListings(location, market, status, priceMin, priceMax, bedsMin, bathsMin, sqftMin, sqftMax, propertyType, sort, page, limit, latMin, latMax, lngMin, lngMax)
            //result shouldBe ("TODO")
        }

    }
}
