/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.TikTokApi
import com.scrapebadger.client.models.HTTPValidationError

class TikTokApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TikTokApi
        //val apiInstance = TikTokApi()

        // to test tiktokGeneralSearch
        should("test tiktokGeneralSearch") {
            // uncomment below to test tiktokGeneralSearch
            //val query : kotlin.String = query_example // kotlin.String | Search keyword
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokGeneralSearch(query, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetCommentReplies
        should("test tiktokGetCommentReplies") {
            // uncomment below to test tiktokGetCommentReplies
            //val commentId : kotlin.String = commentId_example // kotlin.String | 
            //val videoId : kotlin.String = videoId_example // kotlin.String | Parent video id
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Pagination cursor from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokGetCommentReplies(commentId, videoId, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetComments
        should("test tiktokGetComments") {
            // uncomment below to test tiktokGetComments
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Pagination cursor from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokGetComments(videoId, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetFollowersDeprecated
        should("test tiktokGetFollowersDeprecated") {
            // uncomment below to test tiktokGetFollowersDeprecated
            //val username : kotlin.String = username_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokGetFollowersDeprecated(username, region, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetFollowingDeprecated
        should("test tiktokGetFollowingDeprecated") {
            // uncomment below to test tiktokGetFollowingDeprecated
            //val username : kotlin.String = username_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokGetFollowingDeprecated(username, region, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetHashtagDetail
        should("test tiktokGetHashtagDetail") {
            // uncomment below to test tiktokGetHashtagDetail
            //val name : kotlin.String = name_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.tiktokGetHashtagDetail(name, region)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetHashtagVideos
        should("test tiktokGetHashtagVideos") {
            // uncomment below to test tiktokGetHashtagVideos
            //val name : kotlin.String = name_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Pagination cursor from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokGetHashtagVideos(name, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetLikedVideosDeprecated
        should("test tiktokGetLikedVideosDeprecated") {
            // uncomment below to test tiktokGetLikedVideosDeprecated
            //val username : kotlin.String = username_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokGetLikedVideosDeprecated(username, region, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetMusicSoundDetail
        should("test tiktokGetMusicSoundDetail") {
            // uncomment below to test tiktokGetMusicSoundDetail
            //val musicId : kotlin.String = musicId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.tiktokGetMusicSoundDetail(musicId, region)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetMusicVideos
        should("test tiktokGetMusicVideos") {
            // uncomment below to test tiktokGetMusicVideos
            //val musicId : kotlin.String = musicId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Pagination cursor from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokGetMusicVideos(musicId, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetOembedMetadata
        should("test tiktokGetOembedMetadata") {
            // uncomment below to test tiktokGetOembedMetadata
            //val url : kotlin.String = url_example // kotlin.String | Full TikTok video or profile URL
            //val region : kotlin.String = region_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.tiktokGetOembedMetadata(url, region)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetRelatedVideos
        should("test tiktokGetRelatedVideos") {
            // uncomment below to test tiktokGetRelatedVideos
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokGetRelatedVideos(videoId, region, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetReposts
        should("test tiktokGetReposts") {
            // uncomment below to test tiktokGetReposts
            //val username : kotlin.String = username_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokGetReposts(username, region, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetTiktokAdDetail
        should("test tiktokGetTiktokAdDetail") {
            // uncomment below to test tiktokGetTiktokAdDetail
            //val adId : kotlin.String = adId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | EU region code (the Ad Library is EU-only)
            //val result : kotlin.Any = apiInstance.tiktokGetTiktokAdDetail(adId, region)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetTranscript
        should("test tiktokGetTranscript") {
            // uncomment below to test tiktokGetTranscript
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.tiktokGetTranscript(videoId, region)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetUserProfile
        should("test tiktokGetUserProfile") {
            // uncomment below to test tiktokGetUserProfile
            //val username : kotlin.String = username_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | Content region (ISO 3166-1 alpha-2)
            //val result : kotlin.Any = apiInstance.tiktokGetUserProfile(username, region)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetUserVideos
        should("test tiktokGetUserVideos") {
            // uncomment below to test tiktokGetUserVideos
            //val username : kotlin.String = username_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Pagination cursor from a prior page's `pagination.cursor` (signer path only).
            //val result : kotlin.Any = apiInstance.tiktokGetUserVideos(username, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokGetVideoDetail
        should("test tiktokGetVideoDetail") {
            // uncomment below to test tiktokGetVideoDetail
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val region : kotlin.String = region_example // kotlin.String | 
            //val username : kotlin.String = username_example // kotlin.String | Author handle (skips oEmbed lookup)
            //val result : kotlin.Any = apiInstance.tiktokGetVideoDetail(videoId, region, username)
            //result shouldBe ("TODO")
        }

        // to test tiktokHealthCheck
        should("test tiktokHealthCheck") {
            // uncomment below to test tiktokHealthCheck
            //val result : kotlin.Any = apiInstance.tiktokHealthCheck()
            //result shouldBe ("TODO")
        }

        // to test tiktokHealthCheckHead
        should("test tiktokHealthCheckHead") {
            // uncomment below to test tiktokHealthCheckHead
            //val result : kotlin.Any = apiInstance.tiktokHealthCheckHead()
            //result shouldBe ("TODO")
        }

        // to test tiktokListRegions
        should("test tiktokListRegions") {
            // uncomment below to test tiktokListRegions
            //val result : kotlin.Any = apiInstance.tiktokListRegions()
            //result shouldBe ("TODO")
        }

        // to test tiktokSearchHashtags
        should("test tiktokSearchHashtags") {
            // uncomment below to test tiktokSearchHashtags
            //val query : kotlin.String = query_example // kotlin.String | Search keyword
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokSearchHashtags(query, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokSearchTheTiktokAdLibrary
        should("test tiktokSearchTheTiktokAdLibrary") {
            // uncomment below to test tiktokSearchTheTiktokAdLibrary
            //val query : kotlin.String = query_example // kotlin.String | Keyword (ignored when advertiser_id is set)
            //val advertiserId : kotlin.String = advertiserId_example // kotlin.String | Advertiser business id(s) for advertiser search
            //val region : kotlin.String = region_example // kotlin.String | EU region code (the Ad Library is EU-only)
            //val days : kotlin.Int = 56 // kotlin.Int | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val searchId : kotlin.String = searchId_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokSearchTheTiktokAdLibrary(query, advertiserId, region, days, sort, offset, searchId, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokSearchTiktokAdvertisers
        should("test tiktokSearchTiktokAdvertisers") {
            // uncomment below to test tiktokSearchTiktokAdvertisers
            //val query : kotlin.String = query_example // kotlin.String | Advertiser name (or partial) to look up
            //val region : kotlin.String = region_example // kotlin.String | EU region code (the Ad Library is EU-only)
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokSearchTiktokAdvertisers(query, region, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokSearchTiktokShopProducts
        should("test tiktokSearchTiktokShopProducts") {
            // uncomment below to test tiktokSearchTiktokShopProducts
            //val q : kotlin.String = q_example // kotlin.String | Keyword, e.g. 'wireless earbuds'
            //val result : kotlin.Any = apiInstance.tiktokSearchTiktokShopProducts(q)
            //result shouldBe ("TODO")
        }

        // to test tiktokSearchUsers
        should("test tiktokSearchUsers") {
            // uncomment below to test tiktokSearchUsers
            //val query : kotlin.String = query_example // kotlin.String | Search keyword
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokSearchUsers(query, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokSearchVideos
        should("test tiktokSearchVideos") {
            // uncomment below to test tiktokSearchVideos
            //val query : kotlin.String = query_example // kotlin.String | Search keyword
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | Composite pagination cursor (offset.search_id) from a prior page's pagination.cursor
            //val result : kotlin.Any = apiInstance.tiktokSearchVideos(query, region, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test tiktokTiktokShopBestSellers
        should("test tiktokTiktokShopBestSellers") {
            // uncomment below to test tiktokTiktokShopBestSellers
            //val count : kotlin.Int = 56 // kotlin.Int | Max products to return
            //val result : kotlin.Any = apiInstance.tiktokTiktokShopBestSellers(count)
            //result shouldBe ("TODO")
        }

        // to test tiktokTiktokShopCategorySubcategoriesTopProducts
        should("test tiktokTiktokShopCategorySubcategoriesTopProducts") {
            // uncomment below to test tiktokTiktokShopCategorySubcategoriesTopProducts
            //val categoryId : kotlin.String = categoryId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.tiktokTiktokShopCategorySubcategoriesTopProducts(categoryId)
            //result shouldBe ("TODO")
        }

        // to test tiktokTiktokShopProductDetail
        should("test tiktokTiktokShopProductDetail") {
            // uncomment below to test tiktokTiktokShopProductDetail
            //val productId : kotlin.String = productId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.tiktokTiktokShopProductDetail(productId)
            //result shouldBe ("TODO")
        }

        // to test tiktokTiktokShopRootCategories
        should("test tiktokTiktokShopRootCategories") {
            // uncomment below to test tiktokTiktokShopRootCategories
            //val result : kotlin.Any = apiInstance.tiktokTiktokShopRootCategories()
            //result shouldBe ("TODO")
        }

        // to test tiktokTrendingHashtags
        should("test tiktokTrendingHashtags") {
            // uncomment below to test tiktokTrendingHashtags
            //val region : kotlin.String = region_example // kotlin.String | 
            //val period : kotlin.Int = 56 // kotlin.Int | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokTrendingHashtags(region, period, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokTrendingSongs
        should("test tiktokTrendingSongs") {
            // uncomment below to test tiktokTrendingSongs
            //val region : kotlin.String = region_example // kotlin.String | 
            //val period : kotlin.Int = 56 // kotlin.Int | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokTrendingSongs(region, period, count)
            //result shouldBe ("TODO")
        }

        // to test tiktokTrendingVideos
        should("test tiktokTrendingVideos") {
            // uncomment below to test tiktokTrendingVideos
            //val region : kotlin.String = region_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.tiktokTrendingVideos(region, count)
            //result shouldBe ("TODO")
        }

    }
}
