/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.TwitterApi
import com.scrapebadger.client.models.BillingLogListResponse
import com.scrapebadger.client.models.FilterRuleCreate
import com.scrapebadger.client.models.FilterRuleDeliveryLogListResponse
import com.scrapebadger.client.models.FilterRuleListResponse
import com.scrapebadger.client.models.FilterRuleResponse
import com.scrapebadger.client.models.FilterRuleUpdate
import com.scrapebadger.client.models.FilterRuleValidateRequest
import com.scrapebadger.client.models.FilterRuleValidateResponse
import com.scrapebadger.client.models.HTTPValidationError
import com.scrapebadger.client.models.PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse
import com.scrapebadger.client.models.StreamMonitorCreate
import com.scrapebadger.client.models.StreamMonitorListResponse
import com.scrapebadger.client.models.StreamMonitorResponse
import com.scrapebadger.client.models.StreamMonitorUpdate
import com.scrapebadger.client.models.TweetDeliveryLogListResponse
import com.scrapebadger.client.models.WebhookCreate
import com.scrapebadger.client.models.WebhookListResponse
import com.scrapebadger.client.models.WebhookResponse
import com.scrapebadger.client.models.WebhookTestRequest
import com.scrapebadger.client.models.WebhookTestResponse

class TwitterApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TwitterApi
        //val apiInstance = TwitterApi()

        // to test twitterAdvancedTweetSearch
        should("test twitterAdvancedTweetSearch") {
            // uncomment below to test twitterAdvancedTweetSearch
            //val query : kotlin.String = query_example // kotlin.String | 
            //val queryType : kotlin.String = queryType_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterAdvancedTweetSearch(query, queryType, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterBatchGetUsersByIds
        should("test twitterBatchGetUsersByIds") {
            // uncomment below to test twitterBatchGetUsersByIds
            //val userIds : kotlin.String = userIds_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterBatchGetUsersByIds(userIds)
            //result shouldBe ("TODO")
        }

        // to test twitterBatchGetUsersByUsernames
        should("test twitterBatchGetUsersByUsernames") {
            // uncomment below to test twitterBatchGetUsersByUsernames
            //val usernames : kotlin.String = usernames_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterBatchGetUsersByUsernames(usernames)
            //result shouldBe ("TODO")
        }

        // to test twitterConfigureWebhookOnAMonitor
        should("test twitterConfigureWebhookOnAMonitor") {
            // uncomment below to test twitterConfigureWebhookOnAMonitor
            //val webhookCreate : WebhookCreate =  // WebhookCreate | 
            //val result : WebhookResponse = apiInstance.twitterConfigureWebhookOnAMonitor(webhookCreate)
            //result shouldBe ("TODO")
        }

        // to test twitterCreateFilterRule
        should("test twitterCreateFilterRule") {
            // uncomment below to test twitterCreateFilterRule
            //val filterRuleCreate : FilterRuleCreate =  // FilterRuleCreate | 
            //val result : FilterRuleResponse = apiInstance.twitterCreateFilterRule(filterRuleCreate)
            //result shouldBe ("TODO")
        }

        // to test twitterCreateStreamMonitor
        should("test twitterCreateStreamMonitor") {
            // uncomment below to test twitterCreateStreamMonitor
            //val streamMonitorCreate : StreamMonitorCreate =  // StreamMonitorCreate | 
            //val result : StreamMonitorResponse = apiInstance.twitterCreateStreamMonitor(streamMonitorCreate)
            //result shouldBe ("TODO")
        }

        // to test twitterDeleteFilterRule
        should("test twitterDeleteFilterRule") {
            // uncomment below to test twitterDeleteFilterRule
            //val ruleId : kotlin.String = ruleId_example // kotlin.String | 
            //apiInstance.twitterDeleteFilterRule(ruleId)
        }

        // to test twitterDeleteStreamMonitor
        should("test twitterDeleteStreamMonitor") {
            // uncomment below to test twitterDeleteStreamMonitor
            //val monitorId : kotlin.String = monitorId_example // kotlin.String | 
            //apiInstance.twitterDeleteStreamMonitor(monitorId)
        }

        // to test twitterGetArticleById
        should("test twitterGetArticleById") {
            // uncomment below to test twitterGetArticleById
            //val articleId : kotlin.String = articleId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetArticleById(articleId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetBroadcastDetails
        should("test twitterGetBroadcastDetails") {
            // uncomment below to test twitterGetBroadcastDetails
            //val broadcastId : kotlin.String = broadcastId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetBroadcastDetails(broadcastId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetCommunityDetails
        should("test twitterGetCommunityDetails") {
            // uncomment below to test twitterGetCommunityDetails
            //val communityId : kotlin.String = communityId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetCommunityDetails(communityId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetCommunityNotes
        should("test twitterGetCommunityNotes") {
            // uncomment below to test twitterGetCommunityNotes
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetCommunityNotes(tweetId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetCommunityTweets
        should("test twitterGetCommunityTweets") {
            // uncomment below to test twitterGetCommunityTweets
            //val communityId : kotlin.String = communityId_example // kotlin.String | 
            //val tweetType : kotlin.String = tweetType_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetCommunityTweets(communityId, tweetType, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetFilterRule
        should("test twitterGetFilterRule") {
            // uncomment below to test twitterGetFilterRule
            //val ruleId : kotlin.String = ruleId_example // kotlin.String | 
            //val result : FilterRuleResponse = apiInstance.twitterGetFilterRule(ruleId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetFilterRulePerPollRates
        should("test twitterGetFilterRulePerPollRates") {
            // uncomment below to test twitterGetFilterRulePerPollRates
            //val result : PortalApiRoutersV1TwitterFilterRulesFilterRulePricingResponse = apiInstance.twitterGetFilterRulePerPollRates()
            //result shouldBe ("TODO")
        }

        // to test twitterGetListDetails
        should("test twitterGetListDetails") {
            // uncomment below to test twitterGetListDetails
            //val listId : kotlin.String = listId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetListDetails(listId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetListTweets
        should("test twitterGetListTweets") {
            // uncomment below to test twitterGetListTweets
            //val listId : kotlin.String = listId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetListTweets(listId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetPlaceDetails
        should("test twitterGetPlaceDetails") {
            // uncomment below to test twitterGetPlaceDetails
            //val placeId : kotlin.String = placeId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetPlaceDetails(placeId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetSimilarTweets
        should("test twitterGetSimilarTweets") {
            // uncomment below to test twitterGetSimilarTweets
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetSimilarTweets(tweetId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetSpaceDetails
        should("test twitterGetSpaceDetails") {
            // uncomment below to test twitterGetSpaceDetails
            //val spaceId : kotlin.String = spaceId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetSpaceDetails(spaceId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetStreamMonitor
        should("test twitterGetStreamMonitor") {
            // uncomment below to test twitterGetStreamMonitor
            //val monitorId : kotlin.String = monitorId_example // kotlin.String | 
            //val result : StreamMonitorResponse = apiInstance.twitterGetStreamMonitor(monitorId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTrendingTopics
        should("test twitterGetTrendingTopics") {
            // uncomment below to test twitterGetTrendingTopics
            //val category : kotlin.String = category_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.twitterGetTrendingTopics(category, count)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTrendsByLocation
        should("test twitterGetTrendsByLocation") {
            // uncomment below to test twitterGetTrendsByLocation
            //val woeid : kotlin.String = woeid_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTrendsByLocation(woeid)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetDetails
        should("test twitterGetTweetDetails") {
            // uncomment below to test twitterGetTweetDetails
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetDetails(tweetId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetEditHistory
        should("test twitterGetTweetEditHistory") {
            // uncomment below to test twitterGetTweetEditHistory
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetEditHistory(tweetId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetFavoriters
        should("test twitterGetTweetFavoriters") {
            // uncomment below to test twitterGetTweetFavoriters
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetFavoriters(tweetId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetQuotes
        should("test twitterGetTweetQuotes") {
            // uncomment below to test twitterGetTweetQuotes
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetQuotes(tweetId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetReplies
        should("test twitterGetTweetReplies") {
            // uncomment below to test twitterGetTweetReplies
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetReplies(tweetId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetRetweeters
        should("test twitterGetTweetRetweeters") {
            // uncomment below to test twitterGetTweetRetweeters
            //val tweetId : kotlin.String = tweetId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetRetweeters(tweetId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetTweetsByIds
        should("test twitterGetTweetsByIds") {
            // uncomment below to test twitterGetTweetsByIds
            //val tweets : kotlin.String = tweets_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetTweetsByIds(tweets)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserArticles
        should("test twitterGetUserArticles") {
            // uncomment below to test twitterGetUserArticles
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserArticles(userId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserById
        should("test twitterGetUserById") {
            // uncomment below to test twitterGetUserById
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserById(userId)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserByUsername
        should("test twitterGetUserByUsername") {
            // uncomment below to test twitterGetUserByUsername
            //val username : kotlin.String = username_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserByUsername(username)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserFollowers
        should("test twitterGetUserFollowers") {
            // uncomment below to test twitterGetUserFollowers
            //val username : kotlin.String = username_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserFollowers(username, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserFollowing
        should("test twitterGetUserFollowing") {
            // uncomment below to test twitterGetUserFollowing
            //val username : kotlin.String = username_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserFollowing(username, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserMentions
        should("test twitterGetUserMentions") {
            // uncomment below to test twitterGetUserMentions
            //val username : kotlin.String = username_example // kotlin.String | 
            //val count : kotlin.Int = 56 // kotlin.Int | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserMentions(username, count, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserSubscriptions
        should("test twitterGetUserSubscriptions") {
            // uncomment below to test twitterGetUserSubscriptions
            //val userId : kotlin.String = userId_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserSubscriptions(userId, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterGetUserTweets
        should("test twitterGetUserTweets") {
            // uncomment below to test twitterGetUserTweets
            //val username : kotlin.String = username_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterGetUserTweets(username, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterListBillingLogs
        should("test twitterListBillingLogs") {
            // uncomment below to test twitterListBillingLogs
            //val monitorId : kotlin.String = monitorId_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : BillingLogListResponse = apiInstance.twitterListBillingLogs(monitorId, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test twitterListDeliveryLogsForAFilterRule
        should("test twitterListDeliveryLogsForAFilterRule") {
            // uncomment below to test twitterListDeliveryLogsForAFilterRule
            //val ruleId : kotlin.String = ruleId_example // kotlin.String | 
            //val deliveryStatus : kotlin.String = deliveryStatus_example // kotlin.String | 
            //val authorUsername : kotlin.String = authorUsername_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val result : FilterRuleDeliveryLogListResponse = apiInstance.twitterListDeliveryLogsForAFilterRule(ruleId, deliveryStatus, authorUsername, page, pageSize, sort)
            //result shouldBe ("TODO")
        }

        // to test twitterListFilterRules
        should("test twitterListFilterRules") {
            // uncomment below to test twitterListFilterRules
            //val status : kotlin.String = status_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : FilterRuleListResponse = apiInstance.twitterListFilterRules(status, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test twitterListStreamMonitors
        should("test twitterListStreamMonitors") {
            // uncomment below to test twitterListStreamMonitors
            //val status : kotlin.String = status_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val result : StreamMonitorListResponse = apiInstance.twitterListStreamMonitors(status, page, pageSize)
            //result shouldBe ("TODO")
        }

        // to test twitterListTweetDeliveryLogs
        should("test twitterListTweetDeliveryLogs") {
            // uncomment below to test twitterListTweetDeliveryLogs
            //val monitorId : kotlin.String = monitorId_example // kotlin.String | 
            //val authorUsername : kotlin.String = authorUsername_example // kotlin.String | 
            //val deliveryStatus : kotlin.String = deliveryStatus_example // kotlin.String | 
            //val page : kotlin.Int = 56 // kotlin.Int | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val sort : kotlin.String = sort_example // kotlin.String | 
            //val result : TweetDeliveryLogListResponse = apiInstance.twitterListTweetDeliveryLogs(monitorId, authorUsername, deliveryStatus, page, pageSize, sort)
            //result shouldBe ("TODO")
        }

        // to test twitterListWebhooks
        should("test twitterListWebhooks") {
            // uncomment below to test twitterListWebhooks
            //val monitorId : kotlin.String = monitorId_example // kotlin.String | 
            //val result : WebhookListResponse = apiInstance.twitterListWebhooks(monitorId)
            //result shouldBe ("TODO")
        }

        // to test twitterRemoveWebhookFromMonitor
        should("test twitterRemoveWebhookFromMonitor") {
            // uncomment below to test twitterRemoveWebhookFromMonitor
            //val webhookId : kotlin.String = webhookId_example // kotlin.String | 
            //apiInstance.twitterRemoveWebhookFromMonitor(webhookId)
        }

        // to test twitterSearchCommunities
        should("test twitterSearchCommunities") {
            // uncomment below to test twitterSearchCommunities
            //val query : kotlin.String = query_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterSearchCommunities(query, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterSearchListTweets
        should("test twitterSearchListTweets") {
            // uncomment below to test twitterSearchListTweets
            //val listId : kotlin.String = listId_example // kotlin.String | 
            //val query : kotlin.String = query_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterSearchListTweets(listId, query, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterSearchPlaces
        should("test twitterSearchPlaces") {
            // uncomment below to test twitterSearchPlaces
            //val query : kotlin.String = query_example // kotlin.String | 
            //val lat : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val long : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : kotlin.Any = apiInstance.twitterSearchPlaces(query, lat, long)
            //result shouldBe ("TODO")
        }

        // to test twitterSearchUsers
        should("test twitterSearchUsers") {
            // uncomment below to test twitterSearchUsers
            //val query : kotlin.String = query_example // kotlin.String | 
            //val cursor : kotlin.String = cursor_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.twitterSearchUsers(query, cursor)
            //result shouldBe ("TODO")
        }

        // to test twitterTestWebhookDelivery
        should("test twitterTestWebhookDelivery") {
            // uncomment below to test twitterTestWebhookDelivery
            //val webhookTestRequest : WebhookTestRequest =  // WebhookTestRequest | 
            //val result : WebhookTestResponse = apiInstance.twitterTestWebhookDelivery(webhookTestRequest)
            //result shouldBe ("TODO")
        }

        // to test twitterTwitterScraperHealthCheck
        should("test twitterTwitterScraperHealthCheck") {
            // uncomment below to test twitterTwitterScraperHealthCheck
            //val result : kotlin.Any = apiInstance.twitterTwitterScraperHealthCheck()
            //result shouldBe ("TODO")
        }

        // to test twitterTwitterScraperHealthCheckHead
        should("test twitterTwitterScraperHealthCheckHead") {
            // uncomment below to test twitterTwitterScraperHealthCheckHead
            //val result : kotlin.Any = apiInstance.twitterTwitterScraperHealthCheckHead()
            //result shouldBe ("TODO")
        }

        // to test twitterUpdateFilterRule
        should("test twitterUpdateFilterRule") {
            // uncomment below to test twitterUpdateFilterRule
            //val ruleId : kotlin.String = ruleId_example // kotlin.String | 
            //val filterRuleUpdate : FilterRuleUpdate =  // FilterRuleUpdate | 
            //val result : FilterRuleResponse = apiInstance.twitterUpdateFilterRule(ruleId, filterRuleUpdate)
            //result shouldBe ("TODO")
        }

        // to test twitterUpdateStreamMonitor
        should("test twitterUpdateStreamMonitor") {
            // uncomment below to test twitterUpdateStreamMonitor
            //val monitorId : kotlin.String = monitorId_example // kotlin.String | 
            //val streamMonitorUpdate : StreamMonitorUpdate =  // StreamMonitorUpdate | 
            //val result : StreamMonitorResponse = apiInstance.twitterUpdateStreamMonitor(monitorId, streamMonitorUpdate)
            //result shouldBe ("TODO")
        }

        // to test twitterValidateSearchQuery
        should("test twitterValidateSearchQuery") {
            // uncomment below to test twitterValidateSearchQuery
            //val filterRuleValidateRequest : FilterRuleValidateRequest =  // FilterRuleValidateRequest | 
            //val result : FilterRuleValidateResponse = apiInstance.twitterValidateSearchQuery(filterRuleValidateRequest)
            //result shouldBe ("TODO")
        }

    }
}
