/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.scrapebadger.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.scrapebadger.client.apis.YouTubeApi
import com.scrapebadger.client.models.HTTPValidationError

class YouTubeApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of YouTubeApi
        //val apiInstance = YouTubeApi()

        // to test youtubeBatchVideoDetail
        should("test youtubeBatchVideoDetail") {
            // uncomment below to test youtubeBatchVideoDetail
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.Any = apiInstance.youtubeBatchVideoDetail(requestBody)
            //result shouldBe ("TODO")
        }

        // to test youtubeChannelAbout
        should("test youtubeChannelAbout") {
            // uncomment below to test youtubeChannelAbout
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeChannelAbout(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeChannelPlaylists
        should("test youtubeChannelPlaylists") {
            // uncomment below to test youtubeChannelPlaylists
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeChannelPlaylists(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeChannelShorts
        should("test youtubeChannelShorts") {
            // uncomment below to test youtubeChannelShorts
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeChannelShorts(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeChannelStreams
        should("test youtubeChannelStreams") {
            // uncomment below to test youtubeChannelStreams
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeChannelStreams(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeChannelVideos
        should("test youtubeChannelVideos") {
            // uncomment below to test youtubeChannelVideos
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeChannelVideos(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeCommentReplies
        should("test youtubeCommentReplies") {
            // uncomment below to test youtubeCommentReplies
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val commentId : kotlin.String = commentId_example // kotlin.String | 
            //val continuation : kotlin.String = continuation_example // kotlin.String | Replies continuation token
            //val result : kotlin.Any = apiInstance.youtubeCommentReplies(videoId, commentId, continuation)
            //result shouldBe ("TODO")
        }

        // to test youtubeCommunityPostComments
        should("test youtubeCommunityPostComments") {
            // uncomment below to test youtubeCommunityPostComments
            //val postId : kotlin.String = postId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeCommunityPostComments(postId)
            //result shouldBe ("TODO")
        }

        // to test youtubeCommunityPosts
        should("test youtubeCommunityPosts") {
            // uncomment below to test youtubeCommunityPosts
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeCommunityPosts(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeContentRegions
        should("test youtubeContentRegions") {
            // uncomment below to test youtubeContentRegions
            //val result : kotlin.Any = apiInstance.youtubeContentRegions()
            //result shouldBe ("TODO")
        }

        // to test youtubeGetACommunityPost
        should("test youtubeGetACommunityPost") {
            // uncomment below to test youtubeGetACommunityPost
            //val postId : kotlin.String = postId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeGetACommunityPost(postId)
            //result shouldBe ("TODO")
        }

        // to test youtubeGetAMixRadioQueue
        should("test youtubeGetAMixRadioQueue") {
            // uncomment below to test youtubeGetAMixRadioQueue
            //val playlistId : kotlin.String = playlistId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeGetAMixRadioQueue(playlistId)
            //result shouldBe ("TODO")
        }

        // to test youtubeGetAShort
        should("test youtubeGetAShort") {
            // uncomment below to test youtubeGetAShort
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeGetAShort(videoId)
            //result shouldBe ("TODO")
        }

        // to test youtubeGetChannelDetail
        should("test youtubeGetChannelDetail") {
            // uncomment below to test youtubeGetChannelDetail
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val gl : kotlin.String = gl_example // kotlin.String | 
            //val hl : kotlin.String = hl_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeGetChannelDetail(channelId, gl, hl)
            //result shouldBe ("TODO")
        }

        // to test youtubeGetPlaylistDetail
        should("test youtubeGetPlaylistDetail") {
            // uncomment below to test youtubeGetPlaylistDetail
            //val playlistId : kotlin.String = playlistId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeGetPlaylistDetail(playlistId)
            //result shouldBe ("TODO")
        }

        // to test youtubeGetVideoDetail
        should("test youtubeGetVideoDetail") {
            // uncomment below to test youtubeGetVideoDetail
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val gl : kotlin.String = gl_example // kotlin.String | 
            //val hl : kotlin.String = hl_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeGetVideoDetail(videoId, gl, hl)
            //result shouldBe ("TODO")
        }

        // to test youtubeGuestHomeFeed
        should("test youtubeGuestHomeFeed") {
            // uncomment below to test youtubeGuestHomeFeed
            //val result : kotlin.Any = apiInstance.youtubeGuestHomeFeed()
            //result shouldBe ("TODO")
        }

        // to test youtubeKeywordSuggestions
        should("test youtubeKeywordSuggestions") {
            // uncomment below to test youtubeKeywordSuggestions
            //val query : kotlin.String = query_example // kotlin.String | Partial query prefix
            //val gl : kotlin.String = gl_example // kotlin.String | 
            //val hl : kotlin.String = hl_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeKeywordSuggestions(query, gl, hl)
            //result shouldBe ("TODO")
        }

        // to test youtubeListCaptionTracks
        should("test youtubeListCaptionTracks") {
            // uncomment below to test youtubeListCaptionTracks
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeListCaptionTracks(videoId)
            //result shouldBe ("TODO")
        }

        // to test youtubeLiveChatMessages
        should("test youtubeLiveChatMessages") {
            // uncomment below to test youtubeLiveChatMessages
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val continuation : kotlin.String = continuation_example // kotlin.String | 
            //val replay : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.Any = apiInstance.youtubeLiveChatMessages(videoId, continuation, replay)
            //result shouldBe ("TODO")
        }

        // to test youtubeOembedMetadata
        should("test youtubeOembedMetadata") {
            // uncomment below to test youtubeOembedMetadata
            //val url : kotlin.String = url_example // kotlin.String | A YouTube URL
            //val result : kotlin.Any = apiInstance.youtubeOembedMetadata(url)
            //result shouldBe ("TODO")
        }

        // to test youtubePlaylistItemsPage
        should("test youtubePlaylistItemsPage") {
            // uncomment below to test youtubePlaylistItemsPage
            //val playlistId : kotlin.String = playlistId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubePlaylistItemsPage(playlistId)
            //result shouldBe ("TODO")
        }

        // to test youtubeRelatedVideos
        should("test youtubeRelatedVideos") {
            // uncomment below to test youtubeRelatedVideos
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeRelatedVideos(videoId)
            //result shouldBe ("TODO")
        }

        // to test youtubeResolveHandleUrlToId
        should("test youtubeResolveHandleUrlToId") {
            // uncomment below to test youtubeResolveHandleUrlToId
            //val handle : kotlin.String = handle_example // kotlin.String | 
            //val url : kotlin.String = url_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeResolveHandleUrlToId(handle, url)
            //result shouldBe ("TODO")
        }

        // to test youtubeSearchWithinAChannel
        should("test youtubeSearchWithinAChannel") {
            // uncomment below to test youtubeSearchWithinAChannel
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val query : kotlin.String = query_example // kotlin.String | Search keywords
            //val result : kotlin.Any = apiInstance.youtubeSearchWithinAChannel(channelId, query)
            //result shouldBe ("TODO")
        }

        // to test youtubeSearchYoutube
        should("test youtubeSearchYoutube") {
            // uncomment below to test youtubeSearchYoutube
            //val query : kotlin.String = query_example // kotlin.String | Search keywords
            //val type : kotlin.String = type_example // kotlin.String | video|channel|playlist|movie|all
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | relevance|date|views|rating
            //val uploadDate : kotlin.String = uploadDate_example // kotlin.String | hour|today|week|month|year
            //val duration : kotlin.String = duration_example // kotlin.String | short|medium|long
            //val features : kotlin.String = features_example // kotlin.String | hd,4k,360,vr180,3d,hdr,cc,subtitles,live
            //val gl : kotlin.String = gl_example // kotlin.String | Content region (US, GB, DE…)
            //val hl : kotlin.String = hl_example // kotlin.String | UI language
            //val continuation : kotlin.String = continuation_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeSearchYoutube(query, type, sortBy, uploadDate, duration, features, gl, hl, continuation)
            //result shouldBe ("TODO")
        }

        // to test youtubeSearchYoutubeMusic
        should("test youtubeSearchYoutubeMusic") {
            // uncomment below to test youtubeSearchYoutubeMusic
            //val query : kotlin.String = query_example // kotlin.String | Search keywords
            //val result : kotlin.Any = apiInstance.youtubeSearchYoutubeMusic(query)
            //result shouldBe ("TODO")
        }

        // to test youtubeShortsBySound
        should("test youtubeShortsBySound") {
            // uncomment below to test youtubeShortsBySound
            //val soundId : kotlin.String = soundId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeShortsBySound(soundId)
            //result shouldBe ("TODO")
        }

        // to test youtubeStreamFormats
        should("test youtubeStreamFormats") {
            // uncomment below to test youtubeStreamFormats
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val client : kotlin.String = client_example // kotlin.String | IOS|ANDROID|WEB
            //val result : kotlin.Any = apiInstance.youtubeStreamFormats(videoId, client)
            //result shouldBe ("TODO")
        }

        // to test youtubeSubscriberCountFast
        should("test youtubeSubscriberCountFast") {
            // uncomment below to test youtubeSubscriberCountFast
            //val channelId : kotlin.String = channelId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeSubscriberCountFast(channelId)
            //result shouldBe ("TODO")
        }

        // to test youtubeSupportedMarkets
        should("test youtubeSupportedMarkets") {
            // uncomment below to test youtubeSupportedMarkets
            //val result : kotlin.Any = apiInstance.youtubeSupportedMarkets()
            //result shouldBe ("TODO")
        }

        // to test youtubeTrendingShorts
        should("test youtubeTrendingShorts") {
            // uncomment below to test youtubeTrendingShorts
            //val result : kotlin.Any = apiInstance.youtubeTrendingShorts()
            //result shouldBe ("TODO")
        }

        // to test youtubeTrendingVideos
        should("test youtubeTrendingVideos") {
            // uncomment below to test youtubeTrendingVideos
            //val gl : kotlin.String = gl_example // kotlin.String | 
            //val type : kotlin.String = type_example // kotlin.String | now|music|gaming|movies
            //val result : kotlin.Any = apiInstance.youtubeTrendingVideos(gl, type)
            //result shouldBe ("TODO")
        }

        // to test youtubeUiLanguages
        should("test youtubeUiLanguages") {
            // uncomment below to test youtubeUiLanguages
            //val result : kotlin.Any = apiInstance.youtubeUiLanguages()
            //result shouldBe ("TODO")
        }

        // to test youtubeVideoCategories
        should("test youtubeVideoCategories") {
            // uncomment below to test youtubeVideoCategories
            //val gl : kotlin.String = gl_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeVideoCategories(gl)
            //result shouldBe ("TODO")
        }

        // to test youtubeVideoComments
        should("test youtubeVideoComments") {
            // uncomment below to test youtubeVideoComments
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | top|newest
            //val continuation : kotlin.String = continuation_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeVideoComments(videoId, sortBy, continuation)
            //result shouldBe ("TODO")
        }

        // to test youtubeVideoTranscript
        should("test youtubeVideoTranscript") {
            // uncomment below to test youtubeVideoTranscript
            //val videoId : kotlin.String = videoId_example // kotlin.String | 
            //val language : kotlin.String = language_example // kotlin.String | BCP-47 language code
            //val result : kotlin.Any = apiInstance.youtubeVideoTranscript(videoId, language)
            //result shouldBe ("TODO")
        }

        // to test youtubeVideosUnderAHashtag
        should("test youtubeVideosUnderAHashtag") {
            // uncomment below to test youtubeVideosUnderAHashtag
            //val tag : kotlin.String = tag_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.youtubeVideosUnderAHashtag(tag)
            //result shouldBe ("TODO")
        }

        // to test youtubeYoutubeScraperHealthCheck
        should("test youtubeYoutubeScraperHealthCheck") {
            // uncomment below to test youtubeYoutubeScraperHealthCheck
            //val result : kotlin.Any = apiInstance.youtubeYoutubeScraperHealthCheck()
            //result shouldBe ("TODO")
        }

        // to test youtubeYoutubeScraperHealthCheckHead
        should("test youtubeYoutubeScraperHealthCheckHead") {
            // uncomment below to test youtubeYoutubeScraperHealthCheckHead
            //val result : kotlin.Any = apiInstance.youtubeYoutubeScraperHealthCheckHead()
            //result shouldBe ("TODO")
        }

    }
}
